// Дополнение к components.ts: закрывает пробелы в линейке (APU, партнёрские видеокарты,
// mATX/ITX-платы, компактные корпуса). Правила цен и индексов — как в components.ts.
// У партнёрских видеокарт lengthMm — длина именно этой модели, а не референса.

import type { SeedProduct } from './components'

export const componentsExtra: SeedProduct[] = [
  // ─────────────────────────── Процессоры ───────────────────────────

  {
    slug: 'amd-ryzen-9-9900x3d', kind: 'COMPONENT', category: 'cpu', brand: 'AMD', model: 'Ryzen 9 9900X3D',
    nameRu: 'Процессор AMD Ryzen 9 9900X3D', nameUz: 'Protsessor AMD Ryzen 9 9900X3D', nameEn: 'AMD Ryzen 9 9900X3D Processor',
    priceUzs: 6820000, stock: 3, images: '[]',
    socket: 'AM5', tdpW: 120, coreCount: 12, boostGhz: 5.5, cpuScore: 96, memoryType: 'DDR5',
    specs: '{"threads":"24","l3Cache":"128 MB","process":"4 nm TSMC","baseClock":"4.4 GHz","igpu":"Radeon Graphics","warranty":"36 months"}',
  },
  {
    slug: 'amd-ryzen-5-7600x3d', kind: 'COMPONENT', category: 'cpu', brand: 'AMD', model: 'Ryzen 5 7600X3D',
    nameRu: 'Процессор AMD Ryzen 5 7600X3D', nameUz: 'Protsessor AMD Ryzen 5 7600X3D', nameEn: 'AMD Ryzen 5 7600X3D Processor',
    descRu: 'Шесть ядер и 96 МБ 3D V-Cache — самый доступный вход в игровые X3D-процессоры на AM5.',
    descUz: 'Olti yadro va 96 MB 3D V-Cache — AM5 dagi X3D o‘yin protsessorlariga eng arzon kirish.',
    descEn: 'Six cores and 96 MB of 3D V-Cache — the most affordable way into X3D gaming chips on AM5.',
    priceUzs: 3080000, stock: 7, images: '[]',
    socket: 'AM5', tdpW: 65, coreCount: 6, boostGhz: 4.7, cpuScore: 86, memoryType: 'DDR5',
    specs: '{"threads":"12","l3Cache":"96 MB","process":"5 nm TSMC","baseClock":"4.1 GHz","igpu":"Radeon Graphics","warranty":"36 months"}',
  },
  {
    slug: 'amd-ryzen-7-8700g', kind: 'COMPONENT', category: 'cpu', brand: 'AMD', model: 'Ryzen 7 8700G',
    nameRu: 'Процессор AMD Ryzen 7 8700G', nameUz: 'Protsessor AMD Ryzen 7 8700G', nameEn: 'AMD Ryzen 7 8700G Processor',
    descRu: 'Встроенная Radeon 780M тянет киберспорт в 1080p — можно собрать ПК и докупить видеокарту позже.',
    descUz: 'O‘rnatilgan Radeon 780M kibersportni 1080p da tortadi — kompyuterni yig‘ib, videokartani keyin olish mumkin.',
    descEn: 'The built-in Radeon 780M handles esports at 1080p — build now and add a graphics card later.',
    priceUzs: 3530000, stock: 9, images: '[]',
    socket: 'AM5', tdpW: 65, coreCount: 8, boostGhz: 5.1, cpuScore: 68, memoryType: 'DDR5',
    specs: '{"threads":"16","l3Cache":"16 MB","process":"4 nm TSMC","baseClock":"4.2 GHz","pcie":"4.0","igpu":"Radeon 780M","npu":"16 TOPS","cooler":"Wraith Spire","warranty":"36 months"}',
  },
  {
    slug: 'amd-ryzen-5-8600g', kind: 'COMPONENT', category: 'cpu', brand: 'AMD', model: 'Ryzen 5 8600G',
    nameRu: 'Процессор AMD Ryzen 5 8600G', nameUz: 'Protsessor AMD Ryzen 5 8600G', nameEn: 'AMD Ryzen 5 8600G Processor',
    priceUzs: 2480000, stock: 14, images: '[]',
    socket: 'AM5', tdpW: 65, coreCount: 6, boostGhz: 5.0, cpuScore: 64, memoryType: 'DDR5',
    specs: '{"threads":"12","l3Cache":"16 MB","process":"4 nm TSMC","baseClock":"4.3 GHz","pcie":"4.0","igpu":"Radeon 760M","npu":"16 TOPS","cooler":"Wraith Stealth","warranty":"36 months"}',
  },
  {
    slug: 'amd-ryzen-5-8500g', kind: 'COMPONENT', category: 'cpu', brand: 'AMD', model: 'Ryzen 5 8500G',
    nameRu: 'Процессор AMD Ryzen 5 8500G', nameUz: 'Protsessor AMD Ryzen 5 8500G', nameEn: 'AMD Ryzen 5 8500G Processor',
    priceUzs: 2050000, stock: 17, images: '[]',
    socket: 'AM5', tdpW: 65, coreCount: 6, boostGhz: 5.0, cpuScore: 57, memoryType: 'DDR5',
    specs: '{"threads":"12","cores":"2x Zen 4 + 4x Zen 4c","l3Cache":"16 MB","process":"4 nm TSMC","baseClock":"3.5 GHz","pcie":"4.0","igpu":"Radeon 740M","cooler":"Wraith Stealth","warranty":"36 months"}',
  },
  {
    slug: 'intel-core-i9-14900ks', kind: 'COMPONENT', category: 'cpu', brand: 'Intel', model: 'Core i9-14900KS',
    nameRu: 'Процессор Intel Core i9-14900KS', nameUz: 'Protsessor Intel Core i9-14900KS', nameEn: 'Intel Core i9-14900KS Processor',
    priceUzs: 7760000, stock: 0, images: '[]',
    socket: 'LGA1700', tdpW: 150, coreCount: 24, boostGhz: 6.2, cpuScore: 90, memoryType: 'DDR5',
    specs: '{"threads":"32","cores":"8P + 16E","l3Cache":"36 MB","process":"Intel 7","maxTurboPower":"253 W","igpu":"UHD 770","warranty":"36 months"}',
  },
  {
    slug: 'intel-core-i7-14700f', kind: 'COMPONENT', category: 'cpu', brand: 'Intel', model: 'Core i7-14700F',
    nameRu: 'Процессор Intel Core i7-14700F', nameUz: 'Protsessor Intel Core i7-14700F', nameEn: 'Intel Core i7-14700F Processor',
    priceUzs: 4490000, stock: 11, images: '[]',
    socket: 'LGA1700', tdpW: 65, coreCount: 20, boostGhz: 5.4, cpuScore: 81, memoryType: 'DDR5',
    specs: '{"threads":"28","cores":"8P + 12E","l3Cache":"33 MB","process":"Intel 7","maxTurboPower":"219 W","igpu":"no","warranty":"36 months"}',
  },
  {
    slug: 'intel-core-i5-14400', kind: 'COMPONENT', category: 'cpu', brand: 'Intel', model: 'Core i5-14400',
    nameRu: 'Процессор Intel Core i5-14400', nameUz: 'Protsessor Intel Core i5-14400', nameEn: 'Intel Core i5-14400 Processor',
    priceUzs: 2720000, stock: 19, images: '[]',
    socket: 'LGA1700', tdpW: 65, coreCount: 10, boostGhz: 4.7, cpuScore: 66, memoryType: 'DDR5',
    specs: '{"threads":"16","cores":"6P + 4E","l3Cache":"20 MB","process":"Intel 7","maxTurboPower":"148 W","igpu":"UHD 730","warranty":"36 months"}',
  },
  {
    slug: 'intel-core-ultra-5-225f', kind: 'COMPONENT', category: 'cpu', brand: 'Intel', model: 'Core Ultra 5 225F',
    nameRu: 'Процессор Intel Core Ultra 5 225F', nameUz: 'Protsessor Intel Core Ultra 5 225F', nameEn: 'Intel Core Ultra 5 225F Processor',
    priceUzs: 1980000, stock: 12, images: '[]',
    socket: 'LGA1851', tdpW: 65, coreCount: 10, boostGhz: 4.9, cpuScore: 68, memoryType: 'DDR5',
    specs: '{"threads":"10","cores":"6P + 4E","l3Cache":"20 MB","process":"TSMC N3B","maxTurboPower":"121 W","igpu":"no","npu":"13 TOPS","warranty":"36 months"}',
  },

  // ─────────────────────────── Видеокарты ───────────────────────────

  {
    slug: 'asus-rog-astral-geforce-rtx-5090-32gb-oc', kind: 'COMPONENT', category: 'gpu', brand: 'ASUS', model: 'ROG Astral GeForce RTX 5090 32GB OC',
    nameRu: 'Видеокарта ASUS ROG Astral GeForce RTX 5090 32GB OC', nameUz: 'Videokarta ASUS ROG Astral GeForce RTX 5090 32GB OC', nameEn: 'ASUS ROG Astral GeForce RTX 5090 32GB OC Graphics Card',
    descRu: 'Четыре вентилятора и заводской разгон, но длина 358 мм — проверьте корпус перед покупкой.',
    descUz: 'To‘rtta ventilyator va zavod tezlashtirishi, biroq uzunligi 358 mm — sotib olishdan oldin korpusni tekshiring.',
    descEn: 'Four fans and a factory overclock, but it is 358 mm long — check your case before buying.',
    priceUzs: 56700000, stock: 1, images: '[]',
    vramGb: 32, tdpW: 600, lengthMm: 358, gpuScore: 131, pcieVersion: '5.0',
    specs: '{"memoryType":"GDDR7","memoryBus":"512-bit","boostClock":"2610 MHz","cudaCores":"21760","power":"1x 12V-2x6","outputs":"3x DisplayPort 2.1b, 2x HDMI 2.1b","warranty":"36 months"}',
  },
  {
    slug: 'gigabyte-geforce-rtx-5080-gaming-oc-16gb', kind: 'COMPONENT', category: 'gpu', brand: 'Gigabyte', model: 'GeForce RTX 5080 Gaming OC 16GB',
    nameRu: 'Видеокарта Gigabyte GeForce RTX 5080 Gaming OC 16GB', nameUz: 'Videokarta Gigabyte GeForce RTX 5080 Gaming OC 16GB', nameEn: 'Gigabyte GeForce RTX 5080 Gaming OC 16GB Graphics Card',
    priceUzs: 23060000, stock: 4, images: '[]',
    vramGb: 16, tdpW: 360, lengthMm: 340, gpuScore: 93, pcieVersion: '5.0',
    specs: '{"memoryType":"GDDR7","memoryBus":"256-bit","boostClock":"2730 MHz","cudaCores":"10752","power":"1x 12V-2x6","outputs":"3x DisplayPort 2.1b, 1x HDMI 2.1b","warranty":"36 months"}',
  },
  {
    slug: 'asus-tuf-gaming-geforce-rtx-5070-ti-16gb-oc', kind: 'COMPONENT', category: 'gpu', brand: 'ASUS', model: 'TUF Gaming GeForce RTX 5070 Ti 16GB OC',
    nameRu: 'Видеокарта ASUS TUF Gaming GeForce RTX 5070 Ti 16GB OC', nameUz: 'Videokarta ASUS TUF Gaming GeForce RTX 5070 Ti 16GB OC', nameEn: 'ASUS TUF Gaming GeForce RTX 5070 Ti 16GB OC Graphics Card',
    priceUzs: 15790000, stock: 6, images: '[]',
    vramGb: 16, tdpW: 300, lengthMm: 329, gpuScore: 77, pcieVersion: '5.0',
    specs: '{"memoryType":"GDDR7","memoryBus":"256-bit","boostClock":"2610 MHz","cudaCores":"8960","power":"1x 12V-2x6","outputs":"3x DisplayPort 2.1b, 2x HDMI 2.1b","warranty":"36 months"}',
  },
  {
    slug: 'msi-geforce-rtx-5070-12g-gaming-trio-oc', kind: 'COMPONENT', category: 'gpu', brand: 'MSI', model: 'GeForce RTX 5070 12G Gaming Trio OC',
    nameRu: 'Видеокарта MSI GeForce RTX 5070 12G Gaming Trio OC', nameUz: 'Videokarta MSI GeForce RTX 5070 12G Gaming Trio OC', nameEn: 'MSI GeForce RTX 5070 12G Gaming Trio OC Graphics Card',
    priceUzs: 10570000, stock: 8, images: '[]',
    vramGb: 12, tdpW: 250, lengthMm: 338, gpuScore: 61, pcieVersion: '5.0',
    specs: '{"memoryType":"GDDR7","memoryBus":"192-bit","boostClock":"2625 MHz","cudaCores":"6144","power":"1x 12V-2x6","outputs":"3x DisplayPort 2.1b, 1x HDMI 2.1b","warranty":"36 months"}',
  },
  {
    slug: 'asus-prime-radeon-rx-9070-xt-16gb-oc', kind: 'COMPONENT', category: 'gpu', brand: 'ASUS', model: 'Prime Radeon RX 9070 XT 16GB OC',
    nameRu: 'Видеокарта ASUS Prime Radeon RX 9070 XT 16GB OC', nameUz: 'Videokarta ASUS Prime Radeon RX 9070 XT 16GB OC', nameEn: 'ASUS Prime Radeon RX 9070 XT 16GB OC Graphics Card',
    priceUzs: 10700000, stock: 7, images: '[]',
    vramGb: 16, tdpW: 304, lengthMm: 312, gpuScore: 73, pcieVersion: '5.0',
    specs: '{"memoryType":"GDDR6","memoryBus":"256-bit","boostClock":"3030 MHz","streamProcessors":"4096","power":"3x 8-pin","outputs":"3x DisplayPort 2.1a, 1x HDMI 2.1b","warranty":"36 months"}',
  },
  {
    slug: 'asus-dual-geforce-rtx-5060-ti-16gb-oc', kind: 'COMPONENT', category: 'gpu', brand: 'ASUS', model: 'Dual GeForce RTX 5060 Ti 16GB OC',
    nameRu: 'Видеокарта ASUS Dual GeForce RTX 5060 Ti 16GB OC', nameUz: 'Videokarta ASUS Dual GeForce RTX 5060 Ti 16GB OC', nameEn: 'ASUS Dual GeForce RTX 5060 Ti 16GB OC Graphics Card',
    descRu: 'Компактные 229 мм и 16 ГБ GDDR7 — влезает почти в любой корпус и не упирается в память.',
    descUz: 'Ixcham 229 mm va 16 GB GDDR7 — deyarli har qanday korpusga sig‘adi va xotira yetishmasligini bilmaydi.',
    descEn: 'A compact 229 mm with 16 GB of GDDR7 — fits almost any case and never runs short of memory.',
    priceUzs: 9100000, stock: 15, images: '[]',
    vramGb: 16, tdpW: 180, lengthMm: 229, gpuScore: 46, pcieVersion: '5.0',
    specs: '{"memoryType":"GDDR7","memoryBus":"128-bit","boostClock":"2632 MHz","cudaCores":"4608","power":"1x 8-pin","outputs":"3x DisplayPort 2.1b, 1x HDMI 2.1b","warranty":"36 months"}',
  },
  {
    slug: 'sapphire-pulse-radeon-rx-9060-xt-16gb', kind: 'COMPONENT', category: 'gpu', brand: 'Sapphire', model: 'Pulse Radeon RX 9060 XT 16GB',
    nameRu: 'Видеокарта Sapphire Pulse Radeon RX 9060 XT 16GB', nameUz: 'Videokarta Sapphire Pulse Radeon RX 9060 XT 16GB', nameEn: 'Sapphire Pulse Radeon RX 9060 XT 16GB Graphics Card',
    priceUzs: 6200000, stock: 13, images: '[]',
    vramGb: 16, tdpW: 160, lengthMm: 240, gpuScore: 43, pcieVersion: '5.0',
    specs: '{"memoryType":"GDDR6","memoryBus":"128-bit","boostClock":"3290 MHz","streamProcessors":"2048","power":"1x 8-pin","outputs":"2x DisplayPort 2.1a, 1x HDMI 2.1b","warranty":"36 months"}',
  },
  {
    slug: 'gigabyte-geforce-rtx-5060-windforce-oc-8gb', kind: 'COMPONENT', category: 'gpu', brand: 'Gigabyte', model: 'GeForce RTX 5060 Windforce OC 8GB',
    nameRu: 'Видеокарта Gigabyte GeForce RTX 5060 Windforce OC 8GB', nameUz: 'Videokarta Gigabyte GeForce RTX 5060 Windforce OC 8GB', nameEn: 'Gigabyte GeForce RTX 5060 Windforce OC 8GB Graphics Card',
    priceUzs: 5380000, stock: 20, images: '[]',
    vramGb: 8, tdpW: 145, lengthMm: 199, gpuScore: 37, pcieVersion: '5.0',
    specs: '{"memoryType":"GDDR7","memoryBus":"128-bit","boostClock":"2527 MHz","cudaCores":"3840","power":"1x 8-pin","outputs":"2x DisplayPort 2.1b, 2x HDMI 2.1b","warranty":"36 months"}',
  },
  {
    slug: 'msi-geforce-rtx-4060-ventus-2x-black-8g-oc', kind: 'COMPONENT', category: 'gpu', brand: 'MSI', model: 'GeForce RTX 4060 Ventus 2X Black 8G OC',
    nameRu: 'Видеокарта MSI GeForce RTX 4060 Ventus 2X Black 8G OC', nameUz: 'Videokarta MSI GeForce RTX 4060 Ventus 2X Black 8G OC', nameEn: 'MSI GeForce RTX 4060 Ventus 2X Black 8G OC Graphics Card',
    priceUzs: 5000000, stock: 0, images: '[]',
    vramGb: 8, tdpW: 115, lengthMm: 199, gpuScore: 33, pcieVersion: '4.0',
    specs: '{"memoryType":"GDDR6","memoryBus":"128-bit","boostClock":"2490 MHz","cudaCores":"3072","power":"1x 8-pin","outputs":"3x DisplayPort 1.4a, 1x HDMI 2.1a","warranty":"36 months"}',
  },
  {
    slug: 'asrock-intel-arc-b570-challenger-10gb-oc', kind: 'COMPONENT', category: 'gpu', brand: 'ASRock', model: 'Intel Arc B570 Challenger 10GB OC',
    nameRu: 'Видеокарта ASRock Intel Arc B570 Challenger 10GB OC', nameUz: 'Videokarta ASRock Intel Arc B570 Challenger 10GB OC', nameEn: 'ASRock Intel Arc B570 Challenger 10GB OC Graphics Card',
    descRu: 'Самый доступный способ получить 10 ГБ видеопамяти и XeSS для игр в 1080p.',
    descUz: '1080p o‘yinlar uchun 10 GB videoxotira va XeSS olishning eng arzon yo‘li.',
    descEn: 'The most affordable way to get 10 GB of VRAM and XeSS for 1080p gaming.',
    priceUzs: 3540000, stock: 10, images: '[]',
    vramGb: 10, tdpW: 150, lengthMm: 249, gpuScore: 30, pcieVersion: '4.0',
    specs: '{"memoryType":"GDDR6","memoryBus":"160-bit","boostClock":"2600 MHz","xeCores":"18","power":"1x 8-pin","outputs":"3x DisplayPort 2.1, 1x HDMI 2.1a","warranty":"36 months"}',
  },

  // ─────────────────────────── Материнские платы ───────────────────────────

  {
    slug: 'msi-mpg-x870e-carbon-wifi', kind: 'COMPONENT', category: 'motherboard', brand: 'MSI', model: 'MPG X870E Carbon WiFi',
    nameRu: 'Материнская плата MSI MPG X870E Carbon WiFi', nameUz: 'Ona plata MSI MPG X870E Carbon WiFi', nameEn: 'MSI MPG X870E Carbon WiFi Motherboard',
    priceUzs: 4830000, stock: 3, images: '[]',
    socket: 'AM5', formFactor: 'ATX', chipset: 'X870E', memoryType: 'DDR5', memorySlots: 4, m2Slots: 4, sataPorts: 4,
    specs: '{"vrm":"18+2+1 stages","lan":"5 Gb Ethernet","wifi":"Wi-Fi 7","usb":"2x USB4 Type-C","audio":"ALC4080","warranty":"36 months"}',
  },
  {
    slug: 'asrock-x870-steel-legend-wifi', kind: 'COMPONENT', category: 'motherboard', brand: 'ASRock', model: 'X870 Steel Legend WiFi',
    nameRu: 'Материнская плата ASRock X870 Steel Legend WiFi', nameUz: 'Ona plata ASRock X870 Steel Legend WiFi', nameEn: 'ASRock X870 Steel Legend WiFi Motherboard',
    priceUzs: 2720000, stock: 8, images: '[]',
    socket: 'AM5', formFactor: 'ATX', chipset: 'X870', memoryType: 'DDR5', memorySlots: 4, m2Slots: 3, sataPorts: 4,
    specs: '{"vrm":"14+2+1 stages","lan":"2.5 Gb Ethernet","wifi":"Wi-Fi 7","usb":"1x USB4 Type-C","audio":"ALC1220","warranty":"36 months"}',
  },
  {
    slug: 'asus-tuf-gaming-b850-plus-wifi', kind: 'COMPONENT', category: 'motherboard', brand: 'ASUS', model: 'TUF Gaming B850-Plus WiFi',
    nameRu: 'Материнская плата ASUS TUF Gaming B850-Plus WiFi', nameUz: 'Ona plata ASUS TUF Gaming B850-Plus WiFi', nameEn: 'ASUS TUF Gaming B850-Plus WiFi Motherboard',
    descRu: 'Надёжная AM5-основа на годы: PCIe 5.0 под накопитель, Wi-Fi 7 и три слота M.2.',
    descUz: 'Yillar davomida ishonchli AM5 asos: nakopitel uchun PCIe 5.0, Wi-Fi 7 va uchta M.2 slot.',
    descEn: 'A dependable AM5 base for years to come: PCIe 5.0 for storage, Wi-Fi 7 and three M.2 slots.',
    priceUzs: 2710000, stock: 11, images: '[]',
    socket: 'AM5', formFactor: 'ATX', chipset: 'B850', memoryType: 'DDR5', memorySlots: 4, m2Slots: 3, sataPorts: 4,
    specs: '{"vrm":"14+2+1 stages","lan":"2.5 Gb Ethernet","wifi":"Wi-Fi 7","usb":"1x USB 3.2 Gen2x2 Type-C","audio":"ALC1220P","warranty":"36 months"}',
  },
  {
    slug: 'msi-mag-b650-tomahawk-wifi', kind: 'COMPONENT', category: 'motherboard', brand: 'MSI', model: 'MAG B650 Tomahawk WiFi',
    nameRu: 'Материнская плата MSI MAG B650 Tomahawk WiFi', nameUz: 'Ona plata MSI MAG B650 Tomahawk WiFi', nameEn: 'MSI MAG B650 Tomahawk WiFi Motherboard',
    priceUzs: 2380000, stock: 13, images: '[]',
    socket: 'AM5', formFactor: 'ATX', chipset: 'B650', memoryType: 'DDR5', memorySlots: 4, m2Slots: 3, sataPorts: 6,
    specs: '{"vrm":"14+2+1 stages","lan":"2.5 Gb Ethernet","wifi":"Wi-Fi 6E","usb":"1x USB 3.2 Gen2x2 Type-C","audio":"ALC4080","warranty":"36 months"}',
  },
  {
    slug: 'gigabyte-b650m-aorus-elite-ax', kind: 'COMPONENT', category: 'motherboard', brand: 'Gigabyte', model: 'B650M AORUS Elite AX',
    nameRu: 'Материнская плата Gigabyte B650M AORUS Elite AX', nameUz: 'Ona plata Gigabyte B650M AORUS Elite AX', nameEn: 'Gigabyte B650M AORUS Elite AX Motherboard',
    priceUzs: 2180000, stock: 16, images: '[]',
    socket: 'AM5', formFactor: 'MATX', chipset: 'B650', memoryType: 'DDR5', memorySlots: 4, m2Slots: 2, sataPorts: 4,
    specs: '{"vrm":"14+2+1 stages","lan":"2.5 Gb Ethernet","wifi":"Wi-Fi 6E","usb":"1x USB 3.2 Gen2 Type-C","audio":"ALC897","warranty":"36 months"}',
  },
  {
    slug: 'asrock-b650i-lightning-wifi', kind: 'COMPONENT', category: 'motherboard', brand: 'ASRock', model: 'B650I Lightning WiFi',
    nameRu: 'Материнская плата ASRock B650I Lightning WiFi', nameUz: 'Ona plata ASRock B650I Lightning WiFi', nameEn: 'ASRock B650I Lightning WiFi Motherboard',
    priceUzs: 2310000, stock: 5, images: '[]',
    socket: 'AM5', formFactor: 'ITX', chipset: 'B650', memoryType: 'DDR5', memorySlots: 2, m2Slots: 2, sataPorts: 2,
    specs: '{"vrm":"10+2+1 stages","lan":"2.5 Gb Ethernet","wifi":"Wi-Fi 6E","usb":"1x USB 3.2 Gen2 Type-C","audio":"ALC897","warranty":"36 months"}',
  },
  {
    slug: 'gigabyte-z890-aorus-elite-wifi7', kind: 'COMPONENT', category: 'motherboard', brand: 'Gigabyte', model: 'Z890 AORUS Elite WiFi7',
    nameRu: 'Материнская плата Gigabyte Z890 AORUS Elite WiFi7', nameUz: 'Ona plata Gigabyte Z890 AORUS Elite WiFi7', nameEn: 'Gigabyte Z890 AORUS Elite WiFi7 Motherboard',
    priceUzs: 2590000, oldPriceUzs: 3400000, stock: 6, images: '[]',
    socket: 'LGA1851', formFactor: 'ATX', chipset: 'Z890', memoryType: 'DDR5', memorySlots: 4, m2Slots: 4, sataPorts: 4,
    specs: '{"vrm":"16+1+2 stages","lan":"2.5 Gb Ethernet","wifi":"Wi-Fi 7","usb":"1x USB 3.2 Gen2x2 Type-C","audio":"ALC1220","warranty":"36 months"}',
  },
  {
    slug: 'msi-mag-b860-tomahawk-wifi', kind: 'COMPONENT', category: 'motherboard', brand: 'MSI', model: 'MAG B860 Tomahawk WiFi',
    nameRu: 'Материнская плата MSI MAG B860 Tomahawk WiFi', nameUz: 'Ona plata MSI MAG B860 Tomahawk WiFi', nameEn: 'MSI MAG B860 Tomahawk WiFi Motherboard',
    priceUzs: 2930000, stock: 9, images: '[]',
    socket: 'LGA1851', formFactor: 'ATX', chipset: 'B860', memoryType: 'DDR5', memorySlots: 4, m2Slots: 3, sataPorts: 4,
    specs: '{"vrm":"14+1+1 stages","lan":"5 Gb Ethernet","wifi":"Wi-Fi 7","usb":"1x USB4 Type-C","audio":"ALC897","warranty":"36 months"}',
  },
  {
    slug: 'msi-pro-z790-p-wifi', kind: 'COMPONENT', category: 'motherboard', brand: 'MSI', model: 'PRO Z790-P WiFi',
    nameRu: 'Материнская плата MSI PRO Z790-P WiFi', nameUz: 'Ona plata MSI PRO Z790-P WiFi', nameEn: 'MSI PRO Z790-P WiFi Motherboard',
    priceUzs: 2310000, stock: 0, images: '[]',
    socket: 'LGA1700', formFactor: 'ATX', chipset: 'Z790', memoryType: 'DDR5', memorySlots: 4, m2Slots: 4, sataPorts: 6,
    specs: '{"vrm":"14+1+1 stages","lan":"2.5 Gb Ethernet","wifi":"Wi-Fi 6E","usb":"1x USB 3.2 Gen1 Type-C","audio":"ALC897","warranty":"36 months"}',
  },
  {
    slug: 'msi-mag-b760m-mortar-wifi', kind: 'COMPONENT', category: 'motherboard', brand: 'MSI', model: 'MAG B760M Mortar WiFi',
    nameRu: 'Материнская плата MSI MAG B760M Mortar WiFi', nameUz: 'Ona plata MSI MAG B760M Mortar WiFi', nameEn: 'MSI MAG B760M Mortar WiFi Motherboard',
    priceUzs: 2010000, stock: 12, images: '[]',
    socket: 'LGA1700', formFactor: 'MATX', chipset: 'B760', memoryType: 'DDR5', memorySlots: 4, m2Slots: 2, sataPorts: 4,
    specs: '{"vrm":"12+1+1 stages","lan":"2.5 Gb Ethernet","wifi":"Wi-Fi 6E","usb":"1x USB 3.2 Gen2x2 Type-C","audio":"ALC897","warranty":"36 months"}',
  },

  // ─────────────────────────── Оперативная память ───────────────────────────

  {
    slug: 'g-skill-trident-z5-ck-ddr5-48gb-8200', kind: 'COMPONENT', category: 'ram', brand: 'G.Skill', model: 'Trident Z5 CK 48GB (2x24GB) DDR5-8200',
    nameRu: 'Оперативная память G.Skill Trident Z5 CK 48GB (2x24GB) DDR5-8200', nameUz: 'Operativ xotira G.Skill Trident Z5 CK 48GB (2x24GB) DDR5-8200', nameEn: 'G.Skill Trident Z5 CK 48GB (2x24GB) DDR5-8200 Memory Kit',
    descRu: 'Модули CUDIMM с собственным тактовым драйвером — частоты выше 8000 МТ/с на платах Z890.',
    descUz: 'O‘z takt drayveriga ega CUDIMM modullari — Z890 platalarida 8000 MT/s dan yuqori chastotalar.',
    descEn: 'CUDIMM modules with an on-board clock driver — speeds beyond 8000 MT/s on Z890 boards.',
    priceUzs: 11370000, stock: 4, images: '[]',
    memoryType: 'DDR5', memoryGb: 48, memoryMhz: 8200, memorySticks: 2,
    specs: '{"latency":"CL40","voltage":"1.35 V","profile":"Intel XMP 3.0","heatspreader":"aluminum","warranty":"lifetime"}',
  },
  {
    slug: 'g-skill-trident-z5-neo-rgb-ddr5-64gb-6000', kind: 'COMPONENT', category: 'ram', brand: 'G.Skill', model: 'Trident Z5 Neo RGB 64GB (2x32GB) DDR5-6000',
    nameRu: 'Оперативная память G.Skill Trident Z5 Neo RGB 64GB (2x32GB) DDR5-6000', nameUz: 'Operativ xotira G.Skill Trident Z5 Neo RGB 64GB (2x32GB) DDR5-6000', nameEn: 'G.Skill Trident Z5 Neo RGB 64GB (2x32GB) DDR5-6000 Memory Kit',
    priceUzs: 13920000, stock: 7, images: '[]',
    memoryType: 'DDR5', memoryGb: 64, memoryMhz: 6000, memorySticks: 2,
    specs: '{"latency":"CL30","voltage":"1.40 V","profile":"AMD EXPO","heatspreader":"aluminum,RGB","warranty":"lifetime"}',
  },
  {
    slug: 'kingston-fury-beast-ddr5-64gb-5600', kind: 'COMPONENT', category: 'ram', brand: 'Kingston', model: 'Fury Beast 64GB (2x32GB) DDR5-5600',
    nameRu: 'Оперативная память Kingston Fury Beast 64GB (2x32GB) DDR5-5600', nameUz: 'Operativ xotira Kingston Fury Beast 64GB (2x32GB) DDR5-5600', nameEn: 'Kingston Fury Beast 64GB (2x32GB) DDR5-5600 Memory Kit',
    priceUzs: 13110000, stock: 9, images: '[]',
    memoryType: 'DDR5', memoryGb: 64, memoryMhz: 5600, memorySticks: 2,
    specs: '{"latency":"CL40","voltage":"1.25 V","profile":"Intel XMP 3.0","heatspreader":"aluminum","warranty":"lifetime"}',
  },
  {
    slug: 'corsair-vengeance-rgb-ddr5-48gb-6000', kind: 'COMPONENT', category: 'ram', brand: 'Corsair', model: 'Vengeance RGB 48GB (2x24GB) DDR5-6000',
    nameRu: 'Оперативная память Corsair Vengeance RGB 48GB (2x24GB) DDR5-6000', nameUz: 'Operativ xotira Corsair Vengeance RGB 48GB (2x24GB) DDR5-6000', nameEn: 'Corsair Vengeance RGB 48GB (2x24GB) DDR5-6000 Memory Kit',
    priceUzs: 9020000, stock: 10, images: '[]',
    memoryType: 'DDR5', memoryGb: 48, memoryMhz: 6000, memorySticks: 2,
    specs: '{"latency":"CL36","voltage":"1.35 V","profile":"Intel XMP 3.0","heatspreader":"aluminum,RGB","warranty":"lifetime"}',
  },
  {
    slug: 'teamgroup-t-force-delta-rgb-ddr5-32gb-6000', kind: 'COMPONENT', category: 'ram', brand: 'TeamGroup', model: 'T-Force Delta RGB 32GB (2x16GB) DDR5-6000',
    nameRu: 'Оперативная память TeamGroup T-Force Delta RGB 32GB (2x16GB) DDR5-6000', nameUz: 'Operativ xotira TeamGroup T-Force Delta RGB 32GB (2x16GB) DDR5-6000', nameEn: 'TeamGroup T-Force Delta RGB 32GB (2x16GB) DDR5-6000 Memory Kit',
    priceUzs: 6020000, stock: 15, images: '[]',
    memoryType: 'DDR5', memoryGb: 32, memoryMhz: 6000, memorySticks: 2,
    specs: '{"latency":"CL38","voltage":"1.25 V","profile":"Intel XMP 3.0","heatspreader":"aluminum,RGB","warranty":"lifetime"}',
  },
  {
    slug: 'kingston-fury-beast-ddr5-32gb-5600', kind: 'COMPONENT', category: 'ram', brand: 'Kingston', model: 'Fury Beast 32GB (2x16GB) DDR5-5600',
    nameRu: 'Оперативная память Kingston Fury Beast 32GB (2x16GB) DDR5-5600', nameUz: 'Operativ xotira Kingston Fury Beast 32GB (2x16GB) DDR5-5600', nameEn: 'Kingston Fury Beast 32GB (2x16GB) DDR5-5600 Memory Kit',
    priceUzs: 5690000, stock: 22, images: '[]',
    memoryType: 'DDR5', memoryGb: 32, memoryMhz: 5600, memorySticks: 2,
    specs: '{"latency":"CL36","voltage":"1.25 V","profile":"Intel XMP 3.0","heatspreader":"aluminum","warranty":"lifetime"}',
  },
  {
    slug: 'crucial-pro-ddr5-32gb-5600', kind: 'COMPONENT', category: 'ram', brand: 'Crucial', model: 'Pro 32GB (2x16GB) DDR5-5600',
    nameRu: 'Оперативная память Crucial Pro 32GB (2x16GB) DDR5-5600', nameUz: 'Operativ xotira Crucial Pro 32GB (2x16GB) DDR5-5600', nameEn: 'Crucial Pro 32GB (2x16GB) DDR5-5600 Memory Kit',
    priceUzs: 5620000, stock: 0, images: '[]',
    memoryType: 'DDR5', memoryGb: 32, memoryMhz: 5600, memorySticks: 2,
    specs: '{"latency":"CL46","voltage":"1.10 V","profile":"XMP 3.0 + EXPO","heatspreader":"aluminum","warranty":"lifetime"}',
  },
  {
    slug: 'teamgroup-t-force-vulcan-z-ddr4-32gb-3200', kind: 'COMPONENT', category: 'ram', brand: 'TeamGroup', model: 'T-Force Vulcan Z 32GB (2x16GB) DDR4-3200',
    nameRu: 'Оперативная память TeamGroup T-Force Vulcan Z 32GB (2x16GB) DDR4-3200', nameUz: 'Operativ xotira TeamGroup T-Force Vulcan Z 32GB (2x16GB) DDR4-3200', nameEn: 'TeamGroup T-Force Vulcan Z 32GB (2x16GB) DDR4-3200 Memory Kit',
    priceUzs: 3400000, stock: 24, images: '[]',
    memoryType: 'DDR4', memoryGb: 32, memoryMhz: 3200, memorySticks: 2,
    specs: '{"latency":"CL16","voltage":"1.35 V","profile":"Intel XMP 2.0","heatspreader":"aluminum","warranty":"lifetime"}',
  },

  // ─────────────────────────── Накопители ───────────────────────────

  {
    slug: 'wd-black-sn850x-4tb', kind: 'COMPONENT', category: 'storage', brand: 'WD', model: 'Black SN850X 4TB',
    nameRu: 'Накопитель WD Black SN850X 4TB NVMe', nameUz: 'Saqlash qurilmasi WD Black SN850X 4TB NVMe', nameEn: 'WD Black SN850X 4TB NVMe SSD',
    priceUzs: 9080000, stock: 5, images: '[]',
    storageGb: 4000, storageType: 'NVME',
    specs: '{"interface":"PCIe 4.0 x4","formFactor":"M.2 2280","read":"7300 MB/s","write":"6600 MB/s","tbw":"2400 TB","warranty":"60 months"}',
  },
  {
    slug: 'samsung-9100-pro-1tb', kind: 'COMPONENT', category: 'storage', brand: 'Samsung', model: '9100 PRO 1TB',
    nameRu: 'Накопитель Samsung 9100 PRO 1TB NVMe', nameUz: 'Saqlash qurilmasi Samsung 9100 PRO 1TB NVMe', nameEn: 'Samsung 9100 PRO 1TB NVMe SSD',
    priceUzs: 3270000, stock: 8, images: '[]',
    storageGb: 1000, storageType: 'NVME',
    specs: '{"interface":"PCIe 5.0 x4","formFactor":"M.2 2280","read":"14700 MB/s","write":"13300 MB/s","tbw":"600 TB","warranty":"60 months"}',
  },
  {
    slug: 'crucial-t705-1tb', kind: 'COMPONENT', category: 'storage', brand: 'Crucial', model: 'T705 1TB',
    nameRu: 'Накопитель Crucial T705 1TB NVMe', nameUz: 'Saqlash qurilmasi Crucial T705 1TB NVMe', nameEn: 'Crucial T705 1TB NVMe SSD',
    priceUzs: 3540000, stock: 0, images: '[]',
    storageGb: 1000, storageType: 'NVME',
    specs: '{"interface":"PCIe 5.0 x4","formFactor":"M.2 2280","read":"13600 MB/s","write":"10200 MB/s","tbw":"600 TB","warranty":"60 months"}',
  },
  {
    slug: 'samsung-990-evo-plus-2tb', kind: 'COMPONENT', category: 'storage', brand: 'Samsung', model: '990 EVO Plus 2TB',
    nameRu: 'Накопитель Samsung 990 EVO Plus 2TB NVMe', nameUz: 'Saqlash qurilmasi Samsung 990 EVO Plus 2TB NVMe', nameEn: 'Samsung 990 EVO Plus 2TB NVMe SSD',
    descRu: 'Два терабайта на скорости 7250 МБ/с без перегрева — оптимальный системный диск для игрового ПК.',
    descUz: '7250 MB/s tezlikda qizib ketmasdan ikki terabayt — o‘yin kompyuteri uchun optimal tizim diski.',
    descEn: 'Two terabytes at 7250 MB/s without overheating — the sweet-spot system drive for a gaming PC.',
    priceUzs: 4490000, stock: 16, images: '[]',
    storageGb: 2000, storageType: 'NVME',
    specs: '{"interface":"PCIe 4.0 x4","formFactor":"M.2 2280","read":"7250 MB/s","write":"6300 MB/s","tbw":"1200 TB","warranty":"60 months"}',
  },
  {
    slug: 'wd-blue-sn5000-2tb', kind: 'COMPONENT', category: 'storage', brand: 'WD', model: 'Blue SN5000 2TB',
    nameRu: 'Накопитель WD Blue SN5000 2TB NVMe', nameUz: 'Saqlash qurilmasi WD Blue SN5000 2TB NVMe', nameEn: 'WD Blue SN5000 2TB NVMe SSD',
    priceUzs: 3310000, stock: 12, images: '[]',
    storageGb: 2000, storageType: 'NVME',
    specs: '{"interface":"PCIe 4.0 x4","formFactor":"M.2 2280","read":"5150 MB/s","write":"4850 MB/s","tbw":"900 TB","warranty":"60 months"}',
  },
  {
    slug: 'kingston-nv3-2tb', kind: 'COMPONENT', category: 'storage', brand: 'Kingston', model: 'NV3 2TB',
    nameRu: 'Накопитель Kingston NV3 2TB NVMe', nameUz: 'Saqlash qurilmasi Kingston NV3 2TB NVMe', nameEn: 'Kingston NV3 2TB NVMe SSD',
    priceUzs: 3800000, stock: 23, images: '[]',
    storageGb: 2000, storageType: 'NVME',
    specs: '{"interface":"PCIe 4.0 x4","formFactor":"M.2 2280","read":"6000 MB/s","write":"5000 MB/s","tbw":"640 TB","warranty":"36 months"}',
  },
  {
    slug: 'crucial-t500-1tb', kind: 'COMPONENT', category: 'storage', brand: 'Crucial', model: 'T500 1TB',
    nameRu: 'Накопитель Crucial T500 1TB NVMe', nameUz: 'Saqlash qurilmasi Crucial T500 1TB NVMe', nameEn: 'Crucial T500 1TB NVMe SSD',
    priceUzs: 2380000, stock: 0, images: '[]',
    storageGb: 1000, storageType: 'NVME',
    specs: '{"interface":"PCIe 4.0 x4","formFactor":"M.2 2280","read":"7300 MB/s","write":"6800 MB/s","tbw":"600 TB","warranty":"60 months"}',
  },
  {
    slug: 'samsung-870-evo-2tb', kind: 'COMPONENT', category: 'storage', brand: 'Samsung', model: '870 EVO 2TB',
    nameRu: 'Накопитель Samsung 870 EVO 2TB SATA SSD', nameUz: 'Saqlash qurilmasi Samsung 870 EVO 2TB SATA SSD', nameEn: 'Samsung 870 EVO 2TB SATA SSD',
    priceUzs: 5350000, stock: 6, images: '[]',
    storageGb: 2000, storageType: 'SATA_SSD',
    specs: '{"interface":"SATA III","formFactor":"2.5″","read":"560 MB/s","write":"530 MB/s","tbw":"1200 TB","warranty":"60 months"}',
  },
  {
    slug: 'seagate-barracuda-2tb-hdd', kind: 'COMPONENT', category: 'storage', brand: 'Seagate', model: 'BarraCuda 2TB HDD',
    nameRu: 'Жёсткий диск Seagate BarraCuda 2TB 7200 об/мин', nameUz: 'Qattiq disk Seagate BarraCuda 2TB 7200 ayl/daq', nameEn: 'Seagate BarraCuda 2TB 7200 RPM Hard Drive',
    priceUzs: 1540000, stock: 21, images: '[]',
    storageGb: 2000, storageType: 'HDD',
    specs: '{"interface":"SATA III","formFactor":"3.5″","rpm":"7200","cache":"256 MB","warranty":"24 months"}',
  },

  // ─────────────────────────── Блоки питания ───────────────────────────

  {
    slug: 'corsair-sf1000', kind: 'COMPONENT', category: 'psu', brand: 'Corsair', model: 'SF1000',
    nameRu: 'Блок питания Corsair SF1000 1000W SFX 80+ Platinum', nameUz: 'Quvvat bloki Corsair SF1000 1000W SFX 80+ Platinum', nameEn: 'Corsair SF1000 1000W SFX 80+ Platinum Power Supply',
    descRu: 'Киловатт в формате SFX: питание RTX 5080 в ITX-корпусе без компромиссов.',
    descUz: 'SFX formatida bir kilovatt: ITX korpusda RTX 5080 ni murosasiz quvvatlantirish.',
    descEn: 'A kilowatt in SFX form: power an RTX 5080 inside an ITX case without compromise.',
    priceUzs: 2860000, stock: 4, images: '[]',
    wattage: 1000, has12vhpwr: true,
    specs: '{"certificate":"80 PLUS Platinum","standard":"ATX 3.1","formFactor":"SFX","modular":"full","fan":"92 mm FDB","warranty":"84 months"}',
  },
  {
    slug: 'corsair-rm1000e', kind: 'COMPONENT', category: 'psu', brand: 'Corsair', model: 'RM1000e',
    nameRu: 'Блок питания Corsair RM1000e 1000W 80+ Gold', nameUz: 'Quvvat bloki Corsair RM1000e 1000W 80+ Gold', nameEn: 'Corsair RM1000e 1000W 80+ Gold Power Supply',
    priceUzs: 2310000, stock: 10, images: '[]',
    wattage: 1000, has12vhpwr: true,
    specs: '{"certificate":"80 PLUS Gold","standard":"ATX 3.1","modular":"full","fan":"120 mm","warranty":"84 months"}',
  },
  {
    slug: 'be-quiet-pure-power-12-m-850w', kind: 'COMPONENT', category: 'psu', brand: 'be quiet!', model: 'Pure Power 12 M 850W',
    nameRu: 'Блок питания be quiet! Pure Power 12 M 850W 80+ Gold', nameUz: 'Quvvat bloki be quiet! Pure Power 12 M 850W 80+ Gold', nameEn: 'be quiet! Pure Power 12 M 850W 80+ Gold Power Supply',
    priceUzs: 1890000, stock: 13, images: '[]',
    wattage: 850, has12vhpwr: true,
    specs: '{"certificate":"80 PLUS Gold","standard":"ATX 3.0","modular":"full","fan":"120 mm","warranty":"120 months"}',
  },
  {
    slug: 'corsair-rm850e', kind: 'COMPONENT', category: 'psu', brand: 'Corsair', model: 'RM850e',
    nameRu: 'Блок питания Corsair RM850e 850W 80+ Gold', nameUz: 'Quvvat bloki Corsair RM850e 850W 80+ Gold', nameEn: 'Corsair RM850e 850W 80+ Gold Power Supply',
    priceUzs: 1680000, stock: 18, images: '[]',
    wattage: 850, has12vhpwr: true,
    specs: '{"certificate":"80 PLUS Gold","standard":"ATX 3.1","modular":"full","fan":"120 mm","warranty":"84 months"}',
  },
  {
    slug: 'msi-mag-a850gl-pcie5', kind: 'COMPONENT', category: 'psu', brand: 'MSI', model: 'MAG A850GL PCIE5',
    nameRu: 'Блок питания MSI MAG A850GL PCIE5 850W 80+ Gold', nameUz: 'Quvvat bloki MSI MAG A850GL PCIE5 850W 80+ Gold', nameEn: 'MSI MAG A850GL PCIE5 850W 80+ Gold Power Supply',
    priceUzs: 1540000, stock: 15, images: '[]',
    wattage: 850, has12vhpwr: true,
    specs: '{"certificate":"80 PLUS Gold","standard":"ATX 3.0","modular":"full","fan":"120 mm","warranty":"120 months"}',
  },
  {
    slug: 'deepcool-pn850m', kind: 'COMPONENT', category: 'psu', brand: 'Deepcool', model: 'PN850M',
    nameRu: 'Блок питания Deepcool PN850M 850W 80+ Gold', nameUz: 'Quvvat bloki Deepcool PN850M 850W 80+ Gold', nameEn: 'Deepcool PN850M 850W 80+ Gold Power Supply',
    priceUzs: 1400000, stock: 0, images: '[]',
    wattage: 850, has12vhpwr: true,
    specs: '{"certificate":"80 PLUS Gold","standard":"ATX 3.1","modular":"full","fan":"120 mm FDB","warranty":"120 months"}',
  },
  {
    slug: 'msi-mag-a750gl-pcie5', kind: 'COMPONENT', category: 'psu', brand: 'MSI', model: 'MAG A750GL PCIE5',
    nameRu: 'Блок питания MSI MAG A750GL PCIE5 750W 80+ Gold', nameUz: 'Quvvat bloki MSI MAG A750GL PCIE5 750W 80+ Gold', nameEn: 'MSI MAG A750GL PCIE5 750W 80+ Gold Power Supply',
    priceUzs: 1190000, stock: 20, images: '[]',
    wattage: 750, has12vhpwr: true,
    specs: '{"certificate":"80 PLUS Gold","standard":"ATX 3.0","modular":"full","fan":"120 mm","warranty":"120 months"}',
  },
  {
    slug: 'deepcool-pk650d', kind: 'COMPONENT', category: 'psu', brand: 'Deepcool', model: 'PK650D',
    nameRu: 'Блок питания Deepcool PK650D 650W 80+ Bronze', nameUz: 'Quvvat bloki Deepcool PK650D 650W 80+ Bronze', nameEn: 'Deepcool PK650D 650W 80+ Bronze Power Supply',
    priceUzs: 840000, stock: 25, images: '[]',
    wattage: 650, has12vhpwr: false,
    specs: '{"certificate":"80 PLUS Bronze","standard":"ATX 2.4","modular":"no","fan":"120 mm","warranty":"60 months"}',
  },

  // ─────────────────────────── Корпуса ───────────────────────────

  {
    slug: 'nzxt-h9-flow', kind: 'COMPONENT', category: 'case', brand: 'NZXT', model: 'H9 Flow',
    nameRu: 'Корпус NZXT H9 Flow', nameUz: 'Korpus NZXT H9 Flow', nameEn: 'NZXT H9 Flow PC Case',
    priceUzs: 2310000, stock: 6, images: '[]',
    lengthMm: 435, heightMm: 165,
    supportsFormFactors: '["ATX","MATX","ITX"]', supportsRadiators: '[240,280,360]',
    specs: '{"type":"Mid Tower","material":"steel,mesh,temperedGlass","fans":"4x 120 mm","psuFormFactor":"ATX","drives":"4x 2.5 + 2x 3.5","warranty":"24 months"}',
  },
  {
    slug: 'montech-air-903-max', kind: 'COMPONENT', category: 'case', brand: 'Montech', model: 'AIR 903 MAX',
    nameRu: 'Корпус Montech AIR 903 MAX', nameUz: 'Korpus Montech AIR 903 MAX', nameEn: 'Montech AIR 903 MAX PC Case',
    descRu: 'Четыре вентилятора 140 мм из коробки и место под видеокарту до 400 мм — продув флагманского уровня за разумные деньги.',
    descUz: 'Qutidan to‘rtta 140 mm ventilyator va 400 mm gacha videokarta uchun joy — maqbul narxda flagman darajasidagi havo oqimi.',
    descEn: 'Four 140 mm fans out of the box and room for a 400 mm graphics card — flagship airflow at a sensible price.',
    priceUzs: 1060000, stock: 9, images: '[]',
    lengthMm: 400, heightMm: 180,
    supportsFormFactors: '["ATX","MATX","ITX"]', supportsRadiators: '[240,280,360]',
    specs: '{"type":"Mid Tower","material":"steel,mesh,temperedGlass","fans":"4x 140 mm","psuFormFactor":"ATX","drives":"2x 2.5 + 2x 3.5","warranty":"24 months"}',
  },
  {
    slug: 'be-quiet-pure-base-500dx', kind: 'COMPONENT', category: 'case', brand: 'be quiet!', model: 'Pure Base 500DX',
    nameRu: 'Корпус be quiet! Pure Base 500DX', nameUz: 'Korpus be quiet! Pure Base 500DX', nameEn: 'be quiet! Pure Base 500DX PC Case',
    priceUzs: 1330000, stock: 8, images: '[]',
    lengthMm: 369, heightMm: 190,
    supportsFormFactors: '["ATX","MATX","ITX"]', supportsRadiators: '[240,280,360]',
    specs: '{"type":"Mid Tower","material":"steel,mesh,temperedGlass","fans":"3x 140 mm Pure Wings 2","psuFormFactor":"ATX","drives":"5x 2.5 + 2x 3.5","warranty":"36 months"}',
  },
  {
    slug: 'cooler-master-nr200p-v2', kind: 'COMPONENT', category: 'case', brand: 'Cooler Master', model: 'MasterBox NR200P V2',
    nameRu: 'Корпус Cooler Master MasterBox NR200P V2 Mini-ITX', nameUz: 'Korpus Cooler Master MasterBox NR200P V2 Mini-ITX', nameEn: 'Cooler Master MasterBox NR200P V2 Mini-ITX PC Case',
    descRu: 'Самый популярный ITX-корпус: башенный кулер до 155 мм и трёхслотовая видеокарта в 18 литрах.',
    descUz: 'Eng ommabop ITX korpus: 18 litrda 155 mm gacha minorali kuler va uch slotli videokarta.',
    descEn: 'The most popular ITX case: a tower cooler up to 155 mm and a triple-slot graphics card in 18 litres.',
    priceUzs: 1540000, stock: 7, images: '[]',
    lengthMm: 334, heightMm: 155,
    supportsFormFactors: '["ITX"]', supportsRadiators: '[240,280]',
    specs: '{"type":"Mini-ITX","volume":"18.25 l","material":"steel,mesh,temperedGlass","fans":"2x 120 mm","psuFormFactor":"SFX / SFX-L","drives":"3x 2.5 + 1x 3.5","warranty":"24 months"}',
  },
  {
    slug: 'corsair-4000d-airflow', kind: 'COMPONENT', category: 'case', brand: 'Corsair', model: '4000D Airflow',
    nameRu: 'Корпус Corsair 4000D Airflow', nameUz: 'Korpus Corsair 4000D Airflow', nameEn: 'Corsair 4000D Airflow PC Case',
    priceUzs: 1730000, stock: 14, images: '[]',
    lengthMm: 360, heightMm: 170,
    supportsFormFactors: '["ATX","MATX","ITX"]', supportsRadiators: '[240,280,360]',
    specs: '{"type":"Mid Tower","material":"steel,mesh,temperedGlass","fans":"2x 120 mm","psuFormFactor":"ATX","drives":"2x 2.5 + 2x 3.5","warranty":"24 months"}',
  },
  {
    slug: 'phanteks-xt-pro-ultra', kind: 'COMPONENT', category: 'case', brand: 'Phanteks', model: 'XT Pro Ultra',
    nameRu: 'Корпус Phanteks XT Pro Ultra', nameUz: 'Korpus Phanteks XT Pro Ultra', nameEn: 'Phanteks XT Pro Ultra PC Case',
    priceUzs: 1230000, stock: 11, images: '[]',
    lengthMm: 420, heightMm: 185,
    supportsFormFactors: '["ATX","MATX","ITX"]', supportsRadiators: '[240,280,360]',
    specs: '{"type":"Mid Tower","material":"steel,mesh,temperedGlass","fans":"4x 140 mm D-RGB","psuFormFactor":"ATX","drives":"2x 2.5 + 2x 3.5","warranty":"60 months"}',
  },
  {
    slug: 'lian-li-lancool-207', kind: 'COMPONENT', category: 'case', brand: 'Lian Li', model: 'Lancool 207',
    nameRu: 'Корпус Lian Li Lancool 207', nameUz: 'Korpus Lian Li Lancool 207', nameEn: 'Lian Li Lancool 207 PC Case',
    priceUzs: 1120000, stock: 17, images: '[]',
    lengthMm: 375, heightMm: 180,
    supportsFormFactors: '["ATX","MATX","ITX"]', supportsRadiators: '[240,280,360]',
    specs: '{"type":"Mid Tower","material":"steel,mesh,temperedGlass","fans":"2x 140 mm ARGB + 2x 120 mm","psuFormFactor":"ATX","drives":"2x 2.5 + 2x 3.5","warranty":"12 months"}',
  },
  {
    slug: 'lian-li-a3-matx', kind: 'COMPONENT', category: 'case', brand: 'Lian Li', model: 'A3-mATX',
    nameRu: 'Корпус Lian Li A3-mATX Micro-ATX', nameUz: 'Korpus Lian Li A3-mATX Micro-ATX', nameEn: 'Lian Li A3-mATX Micro-ATX PC Case',
    priceUzs: 1050000, stock: 0, images: '[]',
    lengthMm: 415, heightMm: 165,
    supportsFormFactors: '["MATX","ITX"]', supportsRadiators: '[240,280,360]',
    specs: '{"type":"Micro Tower","volume":"26.3 l","material":"steel,mesh,temperedGlass","psuFormFactor":"ATX / SFX","drives":"2x 2.5 + 1x 3.5","warranty":"12 months"}',
  },

  // ─────────────────────────── Охлаждение ───────────────────────────

  {
    slug: 'corsair-icue-link-h150i-rgb', kind: 'COMPONENT', category: 'cooler', brand: 'Corsair', model: 'iCUE Link H150i RGB',
    nameRu: 'Система жидкостного охлаждения Corsair iCUE Link H150i RGB 360mm', nameUz: 'Suyuqlikli sovutish tizimi Corsair iCUE Link H150i RGB 360mm', nameEn: 'Corsair iCUE Link H150i RGB 360mm Liquid CPU Cooler',
    priceUzs: 2310000, stock: 5, images: '[]',
    coolerType: 'AIO', coolerTdpW: 300, radiatorMm: 360,
    supportsSockets: '["AM5","AM4","LGA1700","LGA1851"]',
    specs: '{"fans":"3x iCUE Link RX120 RGB","radiatorThickness":"27 mm","warranty":"60 months"}',
  },
  {
    slug: 'nzxt-kraken-240', kind: 'COMPONENT', category: 'cooler', brand: 'NZXT', model: 'Kraken 240',
    nameRu: 'Система жидкостного охлаждения NZXT Kraken 240', nameUz: 'Suyuqlikli sovutish tizimi NZXT Kraken 240', nameEn: 'NZXT Kraken 240 Liquid CPU Cooler',
    priceUzs: 1820000, stock: 8, images: '[]',
    coolerType: 'AIO', coolerTdpW: 250, radiatorMm: 240,
    supportsSockets: '["AM5","AM4","LGA1700","LGA1851"]',
    specs: '{"fans":"2x F120P","pump":"≤ 2800 rpm","radiatorThickness":"27 mm","warranty":"72 months"}',
  },
  {
    slug: 'arctic-liquid-freezer-iii-pro-360', kind: 'COMPONENT', category: 'cooler', brand: 'Arctic', model: 'Liquid Freezer III Pro 360',
    nameRu: 'Система жидкостного охлаждения Arctic Liquid Freezer III Pro 360', nameUz: 'Suyuqlikli sovutish tizimi Arctic Liquid Freezer III Pro 360', nameEn: 'Arctic Liquid Freezer III Pro 360 Liquid CPU Cooler',
    priceUzs: 1400000, oldPriceUzs: 1820000, stock: 12, images: '[]',
    coolerType: 'AIO', coolerTdpW: 350, radiatorMm: 360,
    supportsSockets: '["AM5","AM4","LGA1700","LGA1851"]',
    specs: '{"fans":"3x P12 Pro","radiatorThickness":"38 mm","vrmFan":"yes","warranty":"72 months"}',
  },
  {
    slug: 'noctua-nh-l12s', kind: 'COMPONENT', category: 'cooler', brand: 'Noctua', model: 'NH-L12S',
    nameRu: 'Кулер Noctua NH-L12S низкопрофильный', nameUz: 'Sovutish tizimi Noctua NH-L12S past profilli', nameEn: 'Noctua NH-L12S Low-Profile CPU Cooler',
    priceUzs: 1030000, stock: 6, images: '[]',
    coolerType: 'AIR', coolerTdpW: 95, heightMm: 70,
    supportsSockets: '["AM5","AM4","LGA1700","LGA1851"]',
    specs: '{"fans":"1x NF-A12x15 PWM","heatpipes":"4","noise":"≤ 23.9 dB(A)","warranty":"72 months"}',
  },
  {
    slug: 'thermalright-phantom-spirit-120-se', kind: 'COMPONENT', category: 'cooler', brand: 'Thermalright', model: 'Phantom Spirit 120 SE',
    nameRu: 'Кулер Thermalright Phantom Spirit 120 SE', nameUz: 'Sovutish tizimi Thermalright Phantom Spirit 120 SE', nameEn: 'Thermalright Phantom Spirit 120 SE CPU Cooler',
    priceUzs: 770000, stock: 22, images: '[]',
    coolerType: 'AIR', coolerTdpW: 260, heightMm: 157,
    supportsSockets: '["AM5","AM4","LGA1700","LGA1851"]',
    specs: '{"fans":"2x TL-C12C","heatpipes":"7","noise":"≤ 25.6 dB(A)","warranty":"36 months"}',
  },
  {
    slug: 'thermalright-peerless-assassin-120-se', kind: 'COMPONENT', category: 'cooler', brand: 'Thermalright', model: 'Peerless Assassin 120 SE',
    nameRu: 'Кулер Thermalright Peerless Assassin 120 SE', nameUz: 'Sovutish tizimi Thermalright Peerless Assassin 120 SE', nameEn: 'Thermalright Peerless Assassin 120 SE CPU Cooler',
    descRu: 'Двухбашенный кулер по цене однобашенного — спокойно охлаждает Ryzen 7 и Core i7 под нагрузкой.',
    descUz: 'Bir minorali narxidagi ikki minorali kuler — yuklama ostida Ryzen 7 va Core i7 ni bemalol sovutadi.',
    descEn: 'A dual-tower cooler for the price of a single tower — keeps a Ryzen 7 or Core i7 cool under load.',
    priceUzs: 700000, stock: 25, images: '[]',
    coolerType: 'AIR', coolerTdpW: 245, heightMm: 155,
    supportsSockets: '["AM5","AM4","LGA1700","LGA1851"]',
    specs: '{"fans":"2x TL-C12C","heatpipes":"6","noise":"≤ 25.6 dB(A)","warranty":"36 months"}',
  },
  {
    slug: 'id-cooling-se-224-xts', kind: 'COMPONENT', category: 'cooler', brand: 'ID-Cooling', model: 'SE-224-XTS',
    nameRu: 'Кулер ID-Cooling SE-224-XTS', nameUz: 'Sovutish tizimi ID-Cooling SE-224-XTS', nameEn: 'ID-Cooling SE-224-XTS CPU Cooler',
    priceUzs: 360000, stock: 0, images: '[]',
    coolerType: 'AIR', coolerTdpW: 180, heightMm: 154,
    supportsSockets: '["AM5","AM4","LGA1700"]',
    specs: '{"fans":"1x 120 mm PWM","heatpipes":"4","noise":"≤ 35.2 dB(A)","warranty":"24 months"}',
  },
  {
    slug: 'thermalright-assassin-x-120-refined-se', kind: 'COMPONENT', category: 'cooler', brand: 'Thermalright', model: 'Assassin X 120 Refined SE',
    nameRu: 'Кулер Thermalright Assassin X 120 Refined SE', nameUz: 'Sovutish tizimi Thermalright Assassin X 120 Refined SE', nameEn: 'Thermalright Assassin X 120 Refined SE CPU Cooler',
    priceUzs: 360000, stock: 30, images: '[]',
    coolerType: 'AIR', coolerTdpW: 170, heightMm: 148,
    supportsSockets: '["AM5","AM4","LGA1700","LGA1851"]',
    specs: '{"fans":"1x TL-C12C","heatpipes":"4","noise":"≤ 25.6 dB(A)","warranty":"36 months"}',
  },
]
