// Датасет периферии: мониторы, клавиатуры, мыши, гарнитуры.
// Цены — розница Ташкента: уличная цена в $ × 11 900 плюс 10–20% наценки.
// Значения specs языконезависимы — переводятся только ключи.

import type { SeedProduct } from './components'

export const peripherals: SeedProduct[] = [
  // ─────────────────────────── Мониторы ───────────────────────────
  {
    slug: 'lg-ultragear-27gr95qe', kind: 'PERIPHERAL', category: 'monitor', brand: 'LG', model: 'UltraGear 27GR95QE',
    nameRu: 'Монитор LG UltraGear 27GR95QE 27" OLED 240Hz', nameUz: 'Monitor LG UltraGear 27GR95QE 27" OLED 240Hz', nameEn: 'LG UltraGear 27GR95QE 27" OLED 240Hz Monitor',
    priceUzs: 8910000, stock: 5, images: '[]',
    specs: '{"diagonal":"27\\"","resolution":"2560×1440","refreshRate":"240 Hz","panel":"OLED","responseTime":"0.03 ms","brightness":"200 cd/m²","hdr":"HDR10","adaptiveSync":"G-Sync Compatible, FreeSync Premium","ports":"2× HDMI 2.1, DP 1.4, USB 3.0","warranty":"24 months"}',
  },
  {
    slug: 'lg-ultragear-27gs95qe', kind: 'PERIPHERAL', category: 'monitor', brand: 'LG', model: 'UltraGear 27GS95QE',
    nameRu: 'Монитор LG UltraGear 27GS95QE 27" OLED 240Hz', nameUz: 'Monitor LG UltraGear 27GS95QE 27" OLED 240Hz', nameEn: 'LG UltraGear 27GS95QE 27" OLED 240Hz Monitor',
    descRu: 'WOLED-панель с откликом 0,03 мс: идеально чёрный цвет и никакого шлейфа в быстрых шутерах.',
    descUz: '0,03 ms javob vaqtiga ega WOLED panel: mukammal qora rang va tezkor shuterlarda hech qanday iz qolmaydi.',
    descEn: 'A WOLED panel with 0.03 ms response: perfect blacks and zero smearing in fast shooters.',
    priceUzs: 9590000, stock: 7, images: '[]',
    specs: '{"diagonal":"27\\"","resolution":"2560×1440","refreshRate":"240 Hz","panel":"OLED","responseTime":"0.03 ms","brightness":"275 cd/m²","hdr":"DisplayHDR True Black 400","adaptiveSync":"G-Sync Compatible, FreeSync Premium Pro","ports":"2× HDMI 2.1, DP 1.4, USB 3.0","warranty":"24 months"}',
  },
  {
    slug: 'lg-ultragear-32gs95ue', kind: 'PERIPHERAL', category: 'monitor', brand: 'LG', model: 'UltraGear 32GS95UE',
    nameRu: 'Монитор LG UltraGear 32GS95UE 32" OLED 4K 240Hz', nameUz: 'Monitor LG UltraGear 32GS95UE 32" OLED 4K 240Hz', nameEn: 'LG UltraGear 32GS95UE 32" OLED 4K 240Hz Monitor',
    descRu: 'Двойной режим: 4K при 240 Гц для одиночных игр или Full HD при 480 Гц для киберспорта.',
    descUz: 'Ikki rejim: yakka o‘yinlar uchun 240 Hz’da 4K yoki kibersport uchun 480 Hz’da Full HD.',
    descEn: 'Dual mode: 4K at 240 Hz for story games or Full HD at 480 Hz for esports.',
    priceUzs: 16440000, stock: 2, images: '[]',
    specs: '{"diagonal":"31.5\\"","resolution":"3840×2160","refreshRate":"240 Hz / 480 Hz","panel":"OLED","responseTime":"0.03 ms","brightness":"275 cd/m²","hdr":"DisplayHDR True Black 400","adaptiveSync":"G-Sync Compatible, FreeSync Premium Pro","ports":"2× HDMI 2.1, DP 1.4, USB 3.0","warranty":"24 months"}',
  },
  {
    slug: 'lg-ultragear-27gr83q', kind: 'PERIPHERAL', category: 'monitor', brand: 'LG', model: 'UltraGear 27GR83Q-B',
    nameRu: 'Монитор LG UltraGear 27GR83Q-B 27" IPS 240Hz', nameUz: 'Monitor LG UltraGear 27GR83Q-B 27" IPS 240Hz', nameEn: 'LG UltraGear 27GR83Q-B 27" IPS 240Hz Monitor',
    priceUzs: 4800000, stock: 9, images: '[]',
    specs: '{"diagonal":"27\\"","resolution":"2560×1440","refreshRate":"240 Hz","panel":"IPS","responseTime":"1 ms","brightness":"400 cd/m²","hdr":"HDR10","adaptiveSync":"G-Sync Compatible, FreeSync Premium","ports":"2× HDMI 2.0, DP 1.4","warranty":"24 months"}',
  },
  {
    slug: 'lg-ultragear-24gs60f', kind: 'PERIPHERAL', category: 'monitor', brand: 'LG', model: 'UltraGear 24GS60F-B',
    nameRu: 'Монитор LG UltraGear 24GS60F-B 24" IPS 180Hz', nameUz: 'Monitor LG UltraGear 24GS60F-B 24" IPS 180Hz', nameEn: 'LG UltraGear 24GS60F-B 24" IPS 180Hz Monitor',
    priceUzs: 2060000, stock: 21, images: '[]',
    specs: '{"diagonal":"23.8\\"","resolution":"1920×1080","refreshRate":"180 Hz","panel":"IPS","responseTime":"1 ms","brightness":"300 cd/m²","hdr":"HDR10","adaptiveSync":"G-Sync Compatible, FreeSync Premium","ports":"HDMI 2.0, DP 1.4","warranty":"24 months"}',
  },
  {
    slug: 'asus-rog-swift-pg27aqdm', kind: 'PERIPHERAL', category: 'monitor', brand: 'ASUS', model: 'ROG Swift OLED PG27AQDM',
    nameRu: 'Монитор ASUS ROG Swift OLED PG27AQDM 27" OLED 240Hz', nameUz: 'Monitor ASUS ROG Swift OLED PG27AQDM 27" OLED 240Hz', nameEn: 'ASUS ROG Swift OLED PG27AQDM 27" OLED 240Hz Monitor',
    priceUzs: 10960000, stock: 3, images: '[]',
    specs: '{"diagonal":"26.5\\"","resolution":"2560×1440","refreshRate":"240 Hz","panel":"OLED","responseTime":"0.03 ms","brightness":"275 cd/m²","hdr":"HDR10","adaptiveSync":"G-Sync Compatible, FreeSync Premium","ports":"2× HDMI 2.0, DP 1.4, USB 3.2","warranty":"36 months"}',
  },
  {
    slug: 'asus-rog-swift-pg32ucdm', kind: 'PERIPHERAL', category: 'monitor', brand: 'ASUS', model: 'ROG Swift OLED PG32UCDM',
    nameRu: 'Монитор ASUS ROG Swift OLED PG32UCDM 32" QD-OLED 4K 240Hz', nameUz: 'Monitor ASUS ROG Swift OLED PG32UCDM 32" QD-OLED 4K 240Hz', nameEn: 'ASUS ROG Swift OLED PG32UCDM 32" QD-OLED 4K 240Hz Monitor',
    descRu: 'Флагманский 4K QD-OLED с графеновым радиатором и защитой от выгорания — для топовых сборок.',
    descUz: 'Grafen radiatori va kuyishdan himoyaga ega flagman 4K QD-OLED — eng kuchli yig‘malar uchun.',
    descEn: 'A flagship 4K QD-OLED with a graphene heatsink and burn-in protection — made for top-tier builds.',
    priceUzs: 17810000, stock: 0, images: '[]',
    specs: '{"diagonal":"31.5\\"","resolution":"3840×2160","refreshRate":"240 Hz","panel":"QD-OLED","responseTime":"0.03 ms","brightness":"250 cd/m²","hdr":"DisplayHDR True Black 400","adaptiveSync":"G-Sync Compatible, FreeSync Premium Pro","ports":"2× HDMI 2.1, DP 1.4, USB-C","warranty":"36 months"}',
  },
  {
    slug: 'asus-rog-strix-xg27acs', kind: 'PERIPHERAL', category: 'monitor', brand: 'ASUS', model: 'ROG Strix XG27ACS',
    nameRu: 'Монитор ASUS ROG Strix XG27ACS 27" IPS 180Hz', nameUz: 'Monitor ASUS ROG Strix XG27ACS 27" IPS 180Hz', nameEn: 'ASUS ROG Strix XG27ACS 27" IPS 180Hz Monitor',
    priceUzs: 3700000, stock: 12, images: '[]',
    specs: '{"diagonal":"27\\"","resolution":"2560×1440","refreshRate":"180 Hz","panel":"Fast IPS","responseTime":"1 ms","brightness":"400 cd/m²","hdr":"HDR10","adaptiveSync":"G-Sync Compatible, FreeSync Premium","ports":"HDMI 2.0, DP 1.4, USB-C","warranty":"36 months"}',
  },
  {
    slug: 'asus-tuf-gaming-vg249q3a', kind: 'PERIPHERAL', category: 'monitor', brand: 'ASUS', model: 'TUF Gaming VG249Q3A',
    nameRu: 'Монитор ASUS TUF Gaming VG249Q3A 24" IPS 180Hz', nameUz: 'Monitor ASUS TUF Gaming VG249Q3A 24" IPS 180Hz', nameEn: 'ASUS TUF Gaming VG249Q3A 24" IPS 180Hz Monitor',
    priceUzs: 1780000, stock: 24, images: '[]',
    specs: '{"diagonal":"23.8\\"","resolution":"1920×1080","refreshRate":"180 Hz","panel":"Fast IPS","responseTime":"1 ms","brightness":"300 cd/m²","hdr":"no","adaptiveSync":"G-Sync Compatible, FreeSync Premium","ports":"2× HDMI 2.0, DP 1.2","warranty":"36 months"}',
  },
  {
    slug: 'asus-tuf-gaming-vg27aq3a', kind: 'PERIPHERAL', category: 'monitor', brand: 'ASUS', model: 'TUF Gaming VG27AQ3A',
    nameRu: 'Монитор ASUS TUF Gaming VG27AQ3A 27" IPS 180Hz', nameUz: 'Monitor ASUS TUF Gaming VG27AQ3A 27" IPS 180Hz', nameEn: 'ASUS TUF Gaming VG27AQ3A 27" IPS 180Hz Monitor',
    priceUzs: 3150000, stock: 15, images: '[]',
    specs: '{"diagonal":"27\\"","resolution":"2560×1440","refreshRate":"180 Hz","panel":"Fast IPS","responseTime":"1 ms","brightness":"300 cd/m²","hdr":"HDR10","adaptiveSync":"G-Sync Compatible, FreeSync Premium","ports":"2× HDMI 2.0, DP 1.2","warranty":"36 months"}',
  },
  {
    slug: 'samsung-odyssey-oled-g8-g80sd', kind: 'PERIPHERAL', category: 'monitor', brand: 'Samsung', model: 'Odyssey OLED G8 G80SD',
    nameRu: 'Монитор Samsung Odyssey OLED G8 G80SD 32" QD-OLED 4K 240Hz', nameUz: 'Monitor Samsung Odyssey OLED G8 G80SD 32" QD-OLED 4K 240Hz', nameEn: 'Samsung Odyssey OLED G8 G80SD 32" QD-OLED 4K 240Hz Monitor',
    priceUzs: 13700000, stock: 4, images: '[]',
    specs: '{"diagonal":"31.5\\"","resolution":"3840×2160","refreshRate":"240 Hz","panel":"QD-OLED","responseTime":"0.03 ms","brightness":"250 cd/m²","hdr":"DisplayHDR True Black 400","adaptiveSync":"G-Sync Compatible, FreeSync Premium Pro","ports":"2× HDMI 2.1, DP 1.4, USB 3.0","warranty":"36 months"}',
  },
  {
    slug: 'samsung-odyssey-oled-g6-g60sd', kind: 'PERIPHERAL', category: 'monitor', brand: 'Samsung', model: 'Odyssey OLED G6 G60SD',
    nameRu: 'Монитор Samsung Odyssey OLED G6 G60SD 27" QD-OLED 360Hz', nameUz: 'Monitor Samsung Odyssey OLED G6 G60SD 27" QD-OLED 360Hz', nameEn: 'Samsung Odyssey OLED G6 G60SD 27" QD-OLED 360Hz Monitor',
    descRu: '360 Гц на QD-OLED в 1440p — выбор для соревновательных игр, где важен каждый кадр.',
    descUz: '1440p’da QD-OLED va 360 Hz — har bir kadr muhim bo‘lgan musobaqaviy o‘yinlar uchun tanlov.',
    descEn: '360 Hz QD-OLED at 1440p — the pick for competitive games where every frame counts.',
    priceUzs: 9590000, stock: 6, images: '[]',
    specs: '{"diagonal":"27\\"","resolution":"2560×1440","refreshRate":"360 Hz","panel":"QD-OLED","responseTime":"0.03 ms","brightness":"250 cd/m²","hdr":"DisplayHDR True Black 400","adaptiveSync":"G-Sync Compatible, FreeSync Premium Pro","ports":"2× HDMI 2.1, DP 1.4, USB 3.0","warranty":"36 months"}',
  },
  {
    slug: 'samsung-odyssey-g5-ls27cg510', kind: 'PERIPHERAL', category: 'monitor', brand: 'Samsung', model: 'Odyssey G5 LS27CG510',
    nameRu: 'Монитор Samsung Odyssey G5 LS27CG510 27" VA 165Hz', nameUz: 'Monitor Samsung Odyssey G5 LS27CG510 27" VA 165Hz', nameEn: 'Samsung Odyssey G5 LS27CG510 27" VA 165Hz Monitor',
    priceUzs: 3150000, stock: 13, images: '[]',
    specs: '{"diagonal":"27\\"","resolution":"2560×1440","refreshRate":"165 Hz","panel":"VA","responseTime":"1 ms","brightness":"300 cd/m²","hdr":"HDR10","adaptiveSync":"FreeSync Premium","ports":"HDMI 2.0, DP 1.2","warranty":"36 months"}',
  },
  {
    slug: 'samsung-odyssey-g3-ls24dg302', kind: 'PERIPHERAL', category: 'monitor', brand: 'Samsung', model: 'Odyssey G3 LS24DG302',
    nameRu: 'Монитор Samsung Odyssey G3 LS24DG302 24" VA 180Hz', nameUz: 'Monitor Samsung Odyssey G3 LS24DG302 24" VA 180Hz', nameEn: 'Samsung Odyssey G3 LS24DG302 24" VA 180Hz Monitor',
    priceUzs: 2060000, stock: 18, images: '[]',
    specs: '{"diagonal":"24\\"","resolution":"1920×1080","refreshRate":"180 Hz","panel":"VA","responseTime":"1 ms","brightness":"250 cd/m²","hdr":"no","adaptiveSync":"FreeSync Premium","ports":"HDMI 1.4, DP 1.2","warranty":"36 months"}',
  },
  {
    slug: 'msi-mag-271qpx-qd-oled-e2', kind: 'PERIPHERAL', category: 'monitor', brand: 'MSI', model: 'MAG 271QPX QD-OLED E2',
    nameRu: 'Монитор MSI MAG 271QPX QD-OLED E2 27" QD-OLED 240Hz', nameUz: 'Monitor MSI MAG 271QPX QD-OLED E2 27" QD-OLED 240Hz', nameEn: 'MSI MAG 271QPX QD-OLED E2 27" QD-OLED 240Hz Monitor',
    priceUzs: 7540000, stock: 8, images: '[]',
    specs: '{"diagonal":"26.5\\"","resolution":"2560×1440","refreshRate":"240 Hz","panel":"QD-OLED","responseTime":"0.03 ms","brightness":"250 cd/m²","hdr":"DisplayHDR True Black 400","adaptiveSync":"G-Sync Compatible, FreeSync Premium Pro","ports":"2× HDMI 2.1, DP 1.4, USB-C","warranty":"36 months"}',
  },
  {
    slug: 'msi-mag-274qrf-qd-e2', kind: 'PERIPHERAL', category: 'monitor', brand: 'MSI', model: 'MAG 274QRF QD E2',
    nameRu: 'Монитор MSI MAG 274QRF QD E2 27" IPS 180Hz', nameUz: 'Monitor MSI MAG 274QRF QD E2 27" IPS 180Hz', nameEn: 'MSI MAG 274QRF QD E2 27" IPS 180Hz Monitor',
    priceUzs: 3840000, stock: 11, images: '[]',
    specs: '{"diagonal":"27\\"","resolution":"2560×1440","refreshRate":"180 Hz","panel":"Rapid IPS","responseTime":"1 ms","brightness":"400 cd/m²","hdr":"DisplayHDR 400","adaptiveSync":"G-Sync Compatible, FreeSync Premium","ports":"2× HDMI 2.0, DP 1.4, USB-C","warranty":"36 months"}',
  },
  {
    slug: 'msi-g255f', kind: 'PERIPHERAL', category: 'monitor', brand: 'MSI', model: 'G255F',
    nameRu: 'Монитор MSI G255F 25" IPS 180Hz', nameUz: 'Monitor MSI G255F 25" IPS 180Hz', nameEn: 'MSI G255F 25" IPS 180Hz Monitor',
    priceUzs: 1640000, stock: 22, images: '[]',
    specs: '{"diagonal":"24.5\\"","resolution":"1920×1080","refreshRate":"180 Hz","panel":"Rapid IPS","responseTime":"1 ms","brightness":"300 cd/m²","hdr":"no","adaptiveSync":"G-Sync Compatible, FreeSync Premium","ports":"2× HDMI 2.0, DP 1.2","warranty":"36 months"}',
  },
  {
    slug: 'msi-mpg-321urx-qd-oled', kind: 'PERIPHERAL', category: 'monitor', brand: 'MSI', model: 'MPG 321URX QD-OLED',
    nameRu: 'Монитор MSI MPG 321URX QD-OLED 32" 4K 240Hz', nameUz: 'Monitor MSI MPG 321URX QD-OLED 32" 4K 240Hz', nameEn: 'MSI MPG 321URX QD-OLED 32" 4K 240Hz Monitor',
    priceUzs: 13020000, stock: 3, images: '[]',
    specs: '{"diagonal":"31.5\\"","resolution":"3840×2160","refreshRate":"240 Hz","panel":"QD-OLED","responseTime":"0.03 ms","brightness":"250 cd/m²","hdr":"DisplayHDR True Black 400","adaptiveSync":"G-Sync Compatible, FreeSync Premium Pro","ports":"2× HDMI 2.1, DP 1.4, USB-C","warranty":"36 months"}',
  },
  {
    slug: 'gigabyte-aorus-fo27q3', kind: 'PERIPHERAL', category: 'monitor', brand: 'Gigabyte', model: 'AORUS FO27Q3',
    nameRu: 'Монитор Gigabyte AORUS FO27Q3 27" QD-OLED 360Hz', nameUz: 'Monitor Gigabyte AORUS FO27Q3 27" QD-OLED 360Hz', nameEn: 'Gigabyte AORUS FO27Q3 27" QD-OLED 360Hz Monitor',
    priceUzs: 9590000, stock: 4, images: '[]',
    specs: '{"diagonal":"26.5\\"","resolution":"2560×1440","refreshRate":"360 Hz","panel":"QD-OLED","responseTime":"0.03 ms","brightness":"250 cd/m²","hdr":"DisplayHDR True Black 400","adaptiveSync":"G-Sync Compatible, FreeSync Premium Pro","ports":"2× HDMI 2.1, DP 1.4, USB-C","warranty":"36 months"}',
  },
  {
    slug: 'gigabyte-gs27f', kind: 'PERIPHERAL', category: 'monitor', brand: 'Gigabyte', model: 'GS27F',
    nameRu: 'Монитор Gigabyte GS27F 27" IPS 170Hz', nameUz: 'Monitor Gigabyte GS27F 27" IPS 170Hz', nameEn: 'Gigabyte GS27F 27" IPS 170Hz Monitor',
    priceUzs: 1920000, stock: 16, images: '[]',
    specs: '{"diagonal":"27\\"","resolution":"1920×1080","refreshRate":"170 Hz","panel":"SS IPS","responseTime":"1 ms","brightness":"300 cd/m²","hdr":"no","adaptiveSync":"FreeSync Premium","ports":"2× HDMI 2.0, DP 1.2","warranty":"36 months"}',
  },
  {
    slug: 'aoc-24g4x', kind: 'PERIPHERAL', category: 'monitor', brand: 'AOC', model: '24G4X',
    nameRu: 'Монитор AOC 24G4X 24" IPS 180Hz', nameUz: 'Monitor AOC 24G4X 24" IPS 180Hz', nameEn: 'AOC 24G4X 24" IPS 180Hz Monitor',
    descRu: 'Недорогой и быстрый Full HD монитор для первой игровой сборки.',
    descUz: 'Birinchi o‘yin kompyuteri uchun arzon va tezkor Full HD monitor.',
    descEn: 'An affordable, fast Full HD monitor for a first gaming build.',
    priceUzs: 1780000, stock: 25, images: '[]',
    specs: '{"diagonal":"23.8\\"","resolution":"1920×1080","refreshRate":"180 Hz","panel":"Fast IPS","responseTime":"1 ms","brightness":"300 cd/m²","hdr":"HDR10","adaptiveSync":"G-Sync Compatible, FreeSync Premium","ports":"2× HDMI 2.0, DP 1.4","warranty":"36 months"}',
  },
  {
    slug: 'aoc-q27g4x', kind: 'PERIPHERAL', category: 'monitor', brand: 'AOC', model: 'Q27G4X',
    nameRu: 'Монитор AOC Q27G4X 27" IPS 180Hz', nameUz: 'Monitor AOC Q27G4X 27" IPS 180Hz', nameEn: 'AOC Q27G4X 27" IPS 180Hz Monitor',
    priceUzs: 2740000, stock: 17, images: '[]',
    specs: '{"diagonal":"27\\"","resolution":"2560×1440","refreshRate":"180 Hz","panel":"Fast IPS","responseTime":"1 ms","brightness":"300 cd/m²","hdr":"HDR10","adaptiveSync":"G-Sync Compatible, FreeSync Premium","ports":"2× HDMI 2.0, DP 1.4","warranty":"36 months"}',
  },
  {
    slug: 'aoc-agon-pro-ag276qzd', kind: 'PERIPHERAL', category: 'monitor', brand: 'AOC', model: 'AGON PRO AG276QZD',
    nameRu: 'Монитор AOC AGON PRO AG276QZD 27" OLED 240Hz', nameUz: 'Monitor AOC AGON PRO AG276QZD 27" OLED 240Hz', nameEn: 'AOC AGON PRO AG276QZD 27" OLED 240Hz Monitor',
    priceUzs: 8220000, stock: 0, images: '[]',
    specs: '{"diagonal":"26.5\\"","resolution":"2560×1440","refreshRate":"240 Hz","panel":"OLED","responseTime":"0.03 ms","brightness":"200 cd/m²","hdr":"HDR10","adaptiveSync":"G-Sync Compatible, FreeSync Premium Pro","ports":"2× HDMI 2.0, DP 1.4, USB 3.2","warranty":"36 months"}',
  },
  {
    slug: 'alienware-aw2725df', kind: 'PERIPHERAL', category: 'monitor', brand: 'Alienware', model: 'AW2725DF',
    nameRu: 'Монитор Alienware AW2725DF 27" QD-OLED 360Hz', nameUz: 'Monitor Alienware AW2725DF 27" QD-OLED 360Hz', nameEn: 'Alienware AW2725DF 27" QD-OLED 360Hz Monitor',
    priceUzs: 8910000, stock: 5, images: '[]',
    specs: '{"diagonal":"26.7\\"","resolution":"2560×1440","refreshRate":"360 Hz","panel":"QD-OLED","responseTime":"0.03 ms","brightness":"250 cd/m²","hdr":"DisplayHDR True Black 400","adaptiveSync":"G-Sync Compatible, FreeSync Premium Pro","ports":"HDMI 2.1, 2× DP 1.4, USB 3.2","warranty":"36 months"}',
  },
  {
    slug: 'alienware-aw3225qf', kind: 'PERIPHERAL', category: 'monitor', brand: 'Alienware', model: 'AW3225QF',
    nameRu: 'Монитор Alienware AW3225QF 32" QD-OLED 4K 240Hz', nameUz: 'Monitor Alienware AW3225QF 32" QD-OLED 4K 240Hz', nameEn: 'Alienware AW3225QF 32" QD-OLED 4K 240Hz Monitor',
    descRu: 'Изогнутый 4K QD-OLED с радиусом 1700R и Dolby Vision — погружение в кино и игры.',
    descUz: '1700R egilishli va Dolby Vision’li egilgan 4K QD-OLED — kino va o‘yinlarga to‘liq sho‘ng‘ish.',
    descEn: 'A curved 1700R 4K QD-OLED with Dolby Vision for immersive games and films.',
    priceUzs: 13700000, stock: 2, images: '[]',
    specs: '{"diagonal":"31.6\\"","resolution":"3840×2160","refreshRate":"240 Hz","panel":"QD-OLED","responseTime":"0.03 ms","brightness":"250 cd/m²","hdr":"DisplayHDR True Black 400, Dolby Vision","adaptiveSync":"G-Sync Compatible, FreeSync Premium Pro","ports":"2× HDMI 2.1, DP 1.4, USB 3.2","warranty":"36 months"}',
  },
  {
    slug: 'dell-g2724d', kind: 'PERIPHERAL', category: 'monitor', brand: 'Dell', model: 'G2724D',
    nameRu: 'Монитор Dell G2724D 27" IPS 165Hz', nameUz: 'Monitor Dell G2724D 27" IPS 165Hz', nameEn: 'Dell G2724D 27" IPS 165Hz Monitor',
    priceUzs: 3430000, stock: 10, images: '[]',
    specs: '{"diagonal":"27\\"","resolution":"2560×1440","refreshRate":"165 Hz","panel":"Fast IPS","responseTime":"1 ms","brightness":"400 cd/m²","hdr":"DisplayHDR 400","adaptiveSync":"G-Sync Compatible, FreeSync Premium","ports":"2× HDMI 2.0, DP 1.4","warranty":"36 months"}',
  },
  {
    slug: 'benq-zowie-xl2566k', kind: 'PERIPHERAL', category: 'monitor', brand: 'BenQ', model: 'ZOWIE XL2566K',
    nameRu: 'Монитор BenQ ZOWIE XL2566K 25" TN 360Hz', nameUz: 'Monitor BenQ ZOWIE XL2566K 25" TN 360Hz', nameEn: 'BenQ ZOWIE XL2566K 25" TN 360Hz Monitor',
    descRu: 'Турнирный стандарт: TN-панель 360 Гц и технология DyAc⁺ для чёткости в движении.',
    descUz: 'Turnir standarti: 360 Hz TN panel va harakatdagi aniqlik uchun DyAc⁺ texnologiyasi.',
    descEn: 'The tournament standard: a 360 Hz TN panel with DyAc⁺ for crisp motion clarity.',
    priceUzs: 6850000, stock: 4, images: '[]',
    specs: '{"diagonal":"24.5\\"","resolution":"1920×1080","refreshRate":"360 Hz","panel":"TN","responseTime":"0.5 ms","brightness":"320 cd/m²","hdr":"no","adaptiveSync":"no","ports":"3× HDMI 2.0, DP 1.4","warranty":"36 months"}',
  },
  {
    slug: 'benq-mobiuz-ex2710q', kind: 'PERIPHERAL', category: 'monitor', brand: 'BenQ', model: 'MOBIUZ EX2710Q',
    nameRu: 'Монитор BenQ MOBIUZ EX2710Q 27" IPS 165Hz', nameUz: 'Monitor BenQ MOBIUZ EX2710Q 27" IPS 165Hz', nameEn: 'BenQ MOBIUZ EX2710Q 27" IPS 165Hz Monitor',
    priceUzs: 4110000, stock: 7, images: '[]',
    specs: '{"diagonal":"27\\"","resolution":"2560×1440","refreshRate":"165 Hz","panel":"IPS","responseTime":"1 ms","brightness":"400 cd/m²","hdr":"DisplayHDR 400","adaptiveSync":"FreeSync Premium","ports":"2× HDMI 2.0, DP 1.2","warranty":"36 months"}',
  },
  {
    slug: 'xiaomi-mini-led-g-pro-27i', kind: 'PERIPHERAL', category: 'monitor', brand: 'Xiaomi', model: 'Mini LED Gaming Monitor G Pro 27i',
    nameRu: 'Монитор Xiaomi G Pro 27i 27" Mini LED 180Hz', nameUz: 'Monitor Xiaomi G Pro 27i 27" Mini LED 180Hz', nameEn: 'Xiaomi G Pro 27i 27" Mini LED 180Hz Monitor',
    priceUzs: 4110000, stock: 9, images: '[]',
    specs: '{"diagonal":"27\\"","resolution":"2560×1440","refreshRate":"180 Hz","panel":"IPS Mini LED","responseTime":"1 ms","brightness":"1000 cd/m²","hdr":"DisplayHDR 1000","adaptiveSync":"FreeSync Premium","ports":"2× HDMI 2.0, DP 1.4","warranty":"24 months"}',
  },
  {
    slug: 'xiaomi-gaming-monitor-g27i', kind: 'PERIPHERAL', category: 'monitor', brand: 'Xiaomi', model: 'Gaming Monitor G27i',
    nameRu: 'Монитор Xiaomi G27i 27" IPS 165Hz', nameUz: 'Monitor Xiaomi G27i 27" IPS 165Hz', nameEn: 'Xiaomi G27i 27" IPS 165Hz Monitor',
    priceUzs: 1780000, stock: 19, images: '[]',
    specs: '{"diagonal":"27\\"","resolution":"1920×1080","refreshRate":"165 Hz","panel":"IPS","responseTime":"1 ms","brightness":"250 cd/m²","hdr":"no","adaptiveSync":"FreeSync Premium","ports":"HDMI 2.0, DP 1.4","warranty":"24 months"}',
  },

  // ─────────────────────────── Клавиатуры ───────────────────────────
  {
    slug: 'logitech-g-pro-x-tkl-lightspeed', kind: 'PERIPHERAL', category: 'keyboard', brand: 'Logitech', model: 'G Pro X TKL Lightspeed',
    nameRu: 'Клавиатура Logitech G Pro X TKL Lightspeed', nameUz: 'Klaviatura Logitech G Pro X TKL Lightspeed', nameEn: 'Logitech G Pro X TKL Lightspeed Keyboard',
    descRu: 'Беспроводная клавиатура для киберспорта без цифрового блока — больше места для мыши.',
    descUz: 'Raqamli blokisiz kibersport uchun simsiz klaviatura — sichqoncha uchun ko‘proq joy.',
    descEn: 'A wireless tenkeyless esports keyboard that frees up room for your mouse.',
    priceUzs: 2740000, stock: 8, images: '[]',
    specs: '{"layout":"TKL","switches":"GX Brown Tactile","keycaps":"PBT double-shot","connection":"2.4 GHz + Bluetooth + USB-C","backlight":"RGB","pollingRate":"1000 Hz","warranty":"24 months"}',
  },
  {
    slug: 'logitech-g915-x-tkl-lightspeed', kind: 'PERIPHERAL', category: 'keyboard', brand: 'Logitech', model: 'G915 X TKL Lightspeed',
    nameRu: 'Клавиатура Logitech G915 X TKL Lightspeed', nameUz: 'Klaviatura Logitech G915 X TKL Lightspeed', nameEn: 'Logitech G915 X TKL Lightspeed Keyboard',
    priceUzs: 3150000, stock: 5, images: '[]',
    specs: '{"layout":"TKL","switches":"GL Tactile","keycaps":"ABS","connection":"2.4 GHz + Bluetooth + USB-C","backlight":"RGB","pollingRate":"1000 Hz","warranty":"24 months"}',
  },
  {
    slug: 'logitech-g-pro-x-60-lightspeed', kind: 'PERIPHERAL', category: 'keyboard', brand: 'Logitech', model: 'G Pro X 60 Lightspeed',
    nameRu: 'Клавиатура Logitech G Pro X 60 Lightspeed', nameUz: 'Klaviatura Logitech G Pro X 60 Lightspeed', nameEn: 'Logitech G Pro X 60 Lightspeed Keyboard',
    priceUzs: 2470000, stock: 6, images: '[]',
    specs: '{"layout":"60%","switches":"GX Optical Red","keycaps":"PBT double-shot","connection":"2.4 GHz + Bluetooth + USB-C","backlight":"RGB","pollingRate":"1000 Hz","warranty":"24 months"}',
  },
  {
    slug: 'razer-blackwidow-v4-pro', kind: 'PERIPHERAL', category: 'keyboard', brand: 'Razer', model: 'BlackWidow V4 Pro',
    nameRu: 'Клавиатура Razer BlackWidow V4 Pro', nameUz: 'Klaviatura Razer BlackWidow V4 Pro', nameEn: 'Razer BlackWidow V4 Pro Keyboard',
    priceUzs: 3150000, stock: 0, images: '[]',
    specs: '{"layout":"Full-size","switches":"Razer Green","keycaps":"ABS double-shot","connection":"USB-C","backlight":"RGB","pollingRate":"8000 Hz","warranty":"24 months"}',
  },
  {
    slug: 'razer-huntsman-v3-pro-tkl', kind: 'PERIPHERAL', category: 'keyboard', brand: 'Razer', model: 'Huntsman V3 Pro TKL',
    nameRu: 'Клавиатура Razer Huntsman V3 Pro TKL', nameUz: 'Klaviatura Razer Huntsman V3 Pro TKL', nameEn: 'Razer Huntsman V3 Pro TKL Keyboard',
    descRu: 'Аналоговые оптические переключатели с настраиваемой точкой срабатывания и режимом Rapid Trigger.',
    descUz: 'Ishga tushish nuqtasi sozlanadigan va Rapid Trigger rejimiga ega analog optik tugmalar.',
    descEn: 'Analog optical switches with adjustable actuation and a Rapid Trigger mode.',
    priceUzs: 3010000, stock: 7, images: '[]',
    specs: '{"layout":"TKL","switches":"Razer Analog Optical Gen-2","keycaps":"PBT double-shot","connection":"USB-C","backlight":"RGB","pollingRate":"8000 Hz","warranty":"24 months"}',
  },
  {
    slug: 'razer-blackwidow-v4-75', kind: 'PERIPHERAL', category: 'keyboard', brand: 'Razer', model: 'BlackWidow V4 75%',
    nameRu: 'Клавиатура Razer BlackWidow V4 75%', nameUz: 'Klaviatura Razer BlackWidow V4 75%', nameEn: 'Razer BlackWidow V4 75% Keyboard',
    priceUzs: 2600000, stock: 9, images: '[]',
    specs: '{"layout":"75%","switches":"Razer Orange Tactile","keycaps":"ABS double-shot","connection":"USB-C","backlight":"RGB","pollingRate":"1000 Hz","warranty":"24 months"}',
  },
  {
    slug: 'razer-ornata-v3', kind: 'PERIPHERAL', category: 'keyboard', brand: 'Razer', model: 'Ornata V3',
    nameRu: 'Клавиатура Razer Ornata V3', nameUz: 'Klaviatura Razer Ornata V3', nameEn: 'Razer Ornata V3 Keyboard',
    priceUzs: 960000, stock: 14, images: '[]',
    specs: '{"layout":"Full-size","switches":"Razer Mecha-Membrane","keycaps":"ABS","connection":"USB","backlight":"RGB","pollingRate":"1000 Hz","warranty":"24 months"}',
  },
  {
    slug: 'steelseries-apex-pro-tkl-gen-3', kind: 'PERIPHERAL', category: 'keyboard', brand: 'SteelSeries', model: 'Apex Pro TKL Gen 3',
    nameRu: 'Клавиатура SteelSeries Apex Pro TKL Gen 3', nameUz: 'Klaviatura SteelSeries Apex Pro TKL Gen 3', nameEn: 'SteelSeries Apex Pro TKL Gen 3 Keyboard',
    priceUzs: 3010000, stock: 6, images: '[]',
    specs: '{"layout":"TKL","switches":"OmniPoint 3.0","keycaps":"PBT double-shot","connection":"USB-C","backlight":"RGB","pollingRate":"1000 Hz","warranty":"24 months"}',
  },
  {
    slug: 'steelseries-apex-3-tkl', kind: 'PERIPHERAL', category: 'keyboard', brand: 'SteelSeries', model: 'Apex 3 TKL',
    nameRu: 'Клавиатура SteelSeries Apex 3 TKL', nameUz: 'Klaviatura SteelSeries Apex 3 TKL', nameEn: 'SteelSeries Apex 3 TKL Keyboard',
    priceUzs: 620000, stock: 20, images: '[]',
    specs: '{"layout":"TKL","switches":"SteelSeries Whisper-Quiet","keycaps":"ABS","connection":"USB","backlight":"RGB","pollingRate":"1000 Hz","warranty":"24 months"}',
  },
  {
    slug: 'hyperx-alloy-origins-core', kind: 'PERIPHERAL', category: 'keyboard', brand: 'HyperX', model: 'Alloy Origins Core',
    nameRu: 'Клавиатура HyperX Alloy Origins Core', nameUz: 'Klaviatura HyperX Alloy Origins Core', nameEn: 'HyperX Alloy Origins Core Keyboard',
    priceUzs: 1230000, stock: 16, images: '[]',
    specs: '{"layout":"TKL","switches":"HyperX Red","keycaps":"ABS double-shot","connection":"USB-C","backlight":"RGB","pollingRate":"1000 Hz","warranty":"24 months"}',
  },
  {
    slug: 'hyperx-alloy-rise-75', kind: 'PERIPHERAL', category: 'keyboard', brand: 'HyperX', model: 'Alloy Rise 75',
    nameRu: 'Клавиатура HyperX Alloy Rise 75', nameUz: 'Klaviatura HyperX Alloy Rise 75', nameEn: 'HyperX Alloy Rise 75 Keyboard',
    priceUzs: 2330000, stock: 0, images: '[]',
    specs: '{"layout":"75%","switches":"HyperX Linear","keycaps":"PBT double-shot","connection":"USB-C","backlight":"RGB","pollingRate":"1000 Hz","warranty":"24 months"}',
  },
  {
    slug: 'keychron-k8-pro', kind: 'PERIPHERAL', category: 'keyboard', brand: 'Keychron', model: 'K8 Pro',
    nameRu: 'Клавиатура Keychron K8 Pro', nameUz: 'Klaviatura Keychron K8 Pro', nameEn: 'Keychron K8 Pro Keyboard',
    priceUzs: 1510000, stock: 11, images: '[]',
    specs: '{"layout":"TKL","switches":"Gateron G Pro Red","keycaps":"PBT double-shot","connection":"Bluetooth + USB-C","backlight":"RGB","pollingRate":"1000 Hz","warranty":"12 months"}',
  },
  {
    slug: 'keychron-q1-max', kind: 'PERIPHERAL', category: 'keyboard', brand: 'Keychron', model: 'Q1 Max',
    nameRu: 'Клавиатура Keychron Q1 Max', nameUz: 'Klaviatura Keychron Q1 Max', nameEn: 'Keychron Q1 Max Keyboard',
    descRu: 'Цельный алюминиевый корпус, прокладочное крепление и горячая замена переключателей.',
    descUz: 'Yaxlit alyuminiy korpus, gasket mahkamlash va tugmalarni issiq almashtirish imkoniyati.',
    descEn: 'A solid aluminum case, gasket mount and hot-swappable switches.',
    priceUzs: 3010000, stock: 5, images: '[]',
    specs: '{"layout":"75%","switches":"Gateron Jupiter Banana","keycaps":"PBT double-shot","connection":"2.4 GHz + Bluetooth + USB-C","backlight":"RGB","pollingRate":"1000 Hz","warranty":"12 months"}',
  },
  {
    slug: 'keychron-v1-max', kind: 'PERIPHERAL', category: 'keyboard', brand: 'Keychron', model: 'V1 Max',
    nameRu: 'Клавиатура Keychron V1 Max', nameUz: 'Klaviatura Keychron V1 Max', nameEn: 'Keychron V1 Max Keyboard',
    priceUzs: 1370000, stock: 12, images: '[]',
    specs: '{"layout":"75%","switches":"Gateron Jupiter Red","keycaps":"PBT double-shot","connection":"2.4 GHz + Bluetooth + USB-C","backlight":"RGB","pollingRate":"1000 Hz","warranty":"12 months"}',
  },
  {
    slug: 'asus-rog-strix-scope-ii-96-wireless', kind: 'PERIPHERAL', category: 'keyboard', brand: 'ASUS', model: 'ROG Strix Scope II 96 Wireless',
    nameRu: 'Клавиатура ASUS ROG Strix Scope II 96 Wireless', nameUz: 'Klaviatura ASUS ROG Strix Scope II 96 Wireless', nameEn: 'ASUS ROG Strix Scope II 96 Wireless Keyboard',
    priceUzs: 2470000, stock: 7, images: '[]',
    specs: '{"layout":"96%","switches":"ROG NX Snow","keycaps":"PBT double-shot","connection":"2.4 GHz + Bluetooth + USB-C","backlight":"RGB","pollingRate":"1000 Hz","warranty":"24 months"}',
  },
  {
    slug: 'asus-rog-azoth', kind: 'PERIPHERAL', category: 'keyboard', brand: 'ASUS', model: 'ROG Azoth',
    nameRu: 'Клавиатура ASUS ROG Azoth', nameUz: 'Klaviatura ASUS ROG Azoth', nameEn: 'ASUS ROG Azoth Keyboard',
    descRu: 'Кастомная механика из коробки: OLED-дисплей, три слоя шумоизоляции и смазанные переключатели.',
    descUz: 'Qutidan chiqqan zahoti kastom mexanika: OLED displey, uch qatlamli shovqin izolyatsiyasi va moylangan tugmalar.',
    descEn: 'Custom-grade mechanics out of the box: an OLED display, three layers of dampening and lubed switches.',
    priceUzs: 3430000, stock: 3, images: '[]',
    specs: '{"layout":"75%","switches":"ROG NX Red","keycaps":"PBT double-shot","connection":"2.4 GHz + Bluetooth + USB-C","backlight":"RGB","pollingRate":"1000 Hz","warranty":"24 months"}',
  },
  {
    slug: 'corsair-k70-rgb-pro', kind: 'PERIPHERAL', category: 'keyboard', brand: 'Corsair', model: 'K70 RGB PRO',
    nameRu: 'Клавиатура Corsair K70 RGB PRO', nameUz: 'Klaviatura Corsair K70 RGB PRO', nameEn: 'Corsair K70 RGB PRO Keyboard',
    priceUzs: 2330000, stock: 8, images: '[]',
    specs: '{"layout":"Full-size","switches":"Cherry MX Red","keycaps":"PBT double-shot","connection":"USB-C","backlight":"RGB","pollingRate":"8000 Hz","warranty":"24 months"}',
  },
  {
    slug: 'corsair-k65-plus-wireless', kind: 'PERIPHERAL', category: 'keyboard', brand: 'Corsair', model: 'K65 Plus Wireless',
    nameRu: 'Клавиатура Corsair K65 Plus Wireless', nameUz: 'Klaviatura Corsair K65 Plus Wireless', nameEn: 'Corsair K65 Plus Wireless Keyboard',
    priceUzs: 2190000, stock: 6, images: '[]',
    specs: '{"layout":"75%","switches":"Corsair MLX Red","keycaps":"PBT double-shot","connection":"2.4 GHz + Bluetooth + USB-C","backlight":"RGB","pollingRate":"1000 Hz","warranty":"24 months"}',
  },
  {
    slug: 'redragon-k552-kumara', kind: 'PERIPHERAL', category: 'keyboard', brand: 'Redragon', model: 'K552 Kumara',
    nameRu: 'Клавиатура Redragon K552 Kumara', nameUz: 'Klaviatura Redragon K552 Kumara', nameEn: 'Redragon K552 Kumara Keyboard',
    priceUzs: 480000, stock: 25, images: '[]',
    specs: '{"layout":"TKL","switches":"Outemu Red","keycaps":"ABS","connection":"USB","backlight":"RGB","pollingRate":"1000 Hz","warranty":"12 months"}',
  },
  {
    slug: 'redragon-k617-fizz', kind: 'PERIPHERAL', category: 'keyboard', brand: 'Redragon', model: 'K617 Fizz',
    nameRu: 'Клавиатура Redragon K617 Fizz', nameUz: 'Klaviatura Redragon K617 Fizz', nameEn: 'Redragon K617 Fizz Keyboard',
    priceUzs: 480000, stock: 22, images: '[]',
    specs: '{"layout":"60%","switches":"Outemu Red","keycaps":"ABS","connection":"USB-C","backlight":"RGB","pollingRate":"1000 Hz","warranty":"12 months"}',
  },

  // ─────────────────────────── Мыши ───────────────────────────
  // battery "no" — проводная модель без аккумулятора.
  {
    slug: 'logitech-g-pro-x-superlight-2', kind: 'PERIPHERAL', category: 'mouse', brand: 'Logitech', model: 'G Pro X Superlight 2',
    nameRu: 'Мышь Logitech G Pro X Superlight 2', nameUz: 'Sichqoncha Logitech G Pro X Superlight 2', nameEn: 'Logitech G Pro X Superlight 2 Mouse',
    descRu: 'Любимица профи: 60 граммов, сенсор HERO 2 и гибридные переключатели Lightforce.',
    descUz: 'Professionallarning sevimlisi: 60 gramm, HERO 2 sensori va Lightforce gibrid tugmalari.',
    descEn: 'A pro favourite: 60 grams, a HERO 2 sensor and Lightforce hybrid switches.',
    priceUzs: 2190000, stock: 10, images: '[]',
    specs: '{"sensor":"HERO 2","dpi":"32000 DPI","pollingRate":"8000 Hz","weight":"60 g","connection":"2.4 GHz","battery":"95 h","buttons":"5","warranty":"24 months"}',
  },
  {
    slug: 'logitech-g502-x-plus', kind: 'PERIPHERAL', category: 'mouse', brand: 'Logitech', model: 'G502 X Plus',
    nameRu: 'Мышь Logitech G502 X Plus', nameUz: 'Sichqoncha Logitech G502 X Plus', nameEn: 'Logitech G502 X Plus Mouse',
    priceUzs: 2190000, stock: 5, images: '[]',
    specs: '{"sensor":"HERO 25K","dpi":"25600 DPI","pollingRate":"1000 Hz","weight":"106 g","connection":"2.4 GHz","battery":"130 h","buttons":"13","warranty":"24 months"}',
  },
  {
    slug: 'logitech-g305-lightspeed', kind: 'PERIPHERAL', category: 'mouse', brand: 'Logitech', model: 'G305 Lightspeed',
    nameRu: 'Мышь Logitech G305 Lightspeed', nameUz: 'Sichqoncha Logitech G305 Lightspeed', nameEn: 'Logitech G305 Lightspeed Mouse',
    priceUzs: 550000, stock: 23, images: '[]',
    specs: '{"sensor":"HERO","dpi":"12000 DPI","pollingRate":"1000 Hz","weight":"99 g","connection":"2.4 GHz","battery":"250 h","buttons":"6","warranty":"24 months"}',
  },
  {
    slug: 'logitech-g102-lightsync', kind: 'PERIPHERAL', category: 'mouse', brand: 'Logitech', model: 'G102 Lightsync',
    nameRu: 'Мышь Logitech G102 Lightsync', nameUz: 'Sichqoncha Logitech G102 Lightsync', nameEn: 'Logitech G102 Lightsync Mouse',
    priceUzs: 270000, stock: 25, images: '[]',
    specs: '{"sensor":"Logitech Gaming Sensor","dpi":"8000 DPI","pollingRate":"1000 Hz","weight":"85 g","connection":"USB","battery":"no","buttons":"6","warranty":"24 months"}',
  },
  {
    slug: 'logitech-g502-hero', kind: 'PERIPHERAL', category: 'mouse', brand: 'Logitech', model: 'G502 HERO',
    nameRu: 'Мышь Logitech G502 HERO', nameUz: 'Sichqoncha Logitech G502 HERO', nameEn: 'Logitech G502 HERO Mouse',
    priceUzs: 690000, stock: 18, images: '[]',
    specs: '{"sensor":"HERO 25K","dpi":"25600 DPI","pollingRate":"1000 Hz","weight":"121 g","connection":"USB","battery":"no","buttons":"11","warranty":"24 months"}',
  },
  {
    slug: 'razer-deathadder-v3-pro', kind: 'PERIPHERAL', category: 'mouse', brand: 'Razer', model: 'DeathAdder V3 Pro',
    nameRu: 'Мышь Razer DeathAdder V3 Pro', nameUz: 'Sichqoncha Razer DeathAdder V3 Pro', nameEn: 'Razer DeathAdder V3 Pro Mouse',
    priceUzs: 2060000, stock: 7, images: '[]',
    specs: '{"sensor":"Focus Pro 30K","dpi":"30000 DPI","pollingRate":"1000 Hz","weight":"63 g","connection":"2.4 GHz","battery":"90 h","buttons":"5","warranty":"24 months"}',
  },
  {
    slug: 'razer-viper-v3-pro', kind: 'PERIPHERAL', category: 'mouse', brand: 'Razer', model: 'Viper V3 Pro',
    nameRu: 'Мышь Razer Viper V3 Pro', nameUz: 'Sichqoncha Razer Viper V3 Pro', nameEn: 'Razer Viper V3 Pro Mouse',
    descRu: 'Симметричная беспроводная мышь весом 54 г с опросом 8000 Гц в комплекте.',
    descUz: '54 g vaznli simmetrik simsiz sichqoncha, to‘plamda 8000 Hz so‘rov chastotasi bilan.',
    descEn: 'A 54 g symmetrical wireless mouse with 8000 Hz polling right out of the box.',
    priceUzs: 2190000, stock: 0, images: '[]',
    specs: '{"sensor":"Focus Pro 35K","dpi":"35000 DPI","pollingRate":"8000 Hz","weight":"54 g","connection":"2.4 GHz","battery":"95 h","buttons":"6","warranty":"24 months"}',
  },
  {
    slug: 'razer-basilisk-v3', kind: 'PERIPHERAL', category: 'mouse', brand: 'Razer', model: 'Basilisk V3',
    nameRu: 'Мышь Razer Basilisk V3', nameUz: 'Sichqoncha Razer Basilisk V3', nameEn: 'Razer Basilisk V3 Mouse',
    priceUzs: 960000, stock: 12, images: '[]',
    specs: '{"sensor":"Focus+ 26K","dpi":"26000 DPI","pollingRate":"1000 Hz","weight":"101 g","connection":"USB","battery":"no","buttons":"11","warranty":"24 months"}',
  },
  {
    slug: 'razer-deathadder-v3', kind: 'PERIPHERAL', category: 'mouse', brand: 'Razer', model: 'DeathAdder V3',
    nameRu: 'Мышь Razer DeathAdder V3', nameUz: 'Sichqoncha Razer DeathAdder V3', nameEn: 'Razer DeathAdder V3 Mouse',
    priceUzs: 960000, stock: 14, images: '[]',
    specs: '{"sensor":"Focus Pro 30K","dpi":"30000 DPI","pollingRate":"8000 Hz","weight":"59 g","connection":"USB","battery":"no","buttons":"5","warranty":"24 months"}',
  },
  {
    slug: 'razer-cobra', kind: 'PERIPHERAL', category: 'mouse', brand: 'Razer', model: 'Cobra',
    nameRu: 'Мышь Razer Cobra', nameUz: 'Sichqoncha Razer Cobra', nameEn: 'Razer Cobra Mouse',
    priceUzs: 550000, stock: 17, images: '[]',
    specs: '{"sensor":"Razer Optical","dpi":"8500 DPI","pollingRate":"1000 Hz","weight":"58 g","connection":"USB","battery":"no","buttons":"6","warranty":"24 months"}',
  },
  {
    slug: 'steelseries-aerox-5-wireless', kind: 'PERIPHERAL', category: 'mouse', brand: 'SteelSeries', model: 'Aerox 5 Wireless',
    nameRu: 'Мышь SteelSeries Aerox 5 Wireless', nameUz: 'Sichqoncha SteelSeries Aerox 5 Wireless', nameEn: 'SteelSeries Aerox 5 Wireless Mouse',
    descRu: 'Девять кнопок при весе 74 г — удобна и в шутерах, и в MOBA; защита корпуса по IP54.',
    descUz: '74 g vaznda to‘qqizta tugma — shuterlarda ham, MOBA’da ham qulay; korpusi IP54 himoyasiga ega.',
    descEn: 'Nine buttons at 74 g — comfortable in both shooters and MOBAs, with an IP54-rated shell.',
    priceUzs: 1920000, stock: 6, images: '[]',
    specs: '{"sensor":"TrueMove Air","dpi":"18000 DPI","pollingRate":"1000 Hz","weight":"74 g","connection":"2.4 GHz + Bluetooth","battery":"180 h","buttons":"9","warranty":"24 months"}',
  },
  {
    slug: 'steelseries-aerox-3-wireless', kind: 'PERIPHERAL', category: 'mouse', brand: 'SteelSeries', model: 'Aerox 3 Wireless',
    nameRu: 'Мышь SteelSeries Aerox 3 Wireless', nameUz: 'Sichqoncha SteelSeries Aerox 3 Wireless', nameEn: 'SteelSeries Aerox 3 Wireless Mouse',
    priceUzs: 1370000, stock: 9, images: '[]',
    specs: '{"sensor":"TrueMove Air","dpi":"18000 DPI","pollingRate":"1000 Hz","weight":"68 g","connection":"2.4 GHz + Bluetooth","battery":"200 h","buttons":"6","warranty":"24 months"}',
  },
  {
    slug: 'steelseries-rival-3', kind: 'PERIPHERAL', category: 'mouse', brand: 'SteelSeries', model: 'Rival 3',
    nameRu: 'Мышь SteelSeries Rival 3', nameUz: 'Sichqoncha SteelSeries Rival 3', nameEn: 'SteelSeries Rival 3 Mouse',
    priceUzs: 410000, stock: 21, images: '[]',
    specs: '{"sensor":"TrueMove Core","dpi":"8500 DPI","pollingRate":"1000 Hz","weight":"77 g","connection":"USB","battery":"no","buttons":"6","warranty":"24 months"}',
  },
  {
    slug: 'hyperx-pulsefire-haste-2-wireless', kind: 'PERIPHERAL', category: 'mouse', brand: 'HyperX', model: 'Pulsefire Haste 2 Wireless',
    nameRu: 'Мышь HyperX Pulsefire Haste 2 Wireless', nameUz: 'Sichqoncha HyperX Pulsefire Haste 2 Wireless', nameEn: 'HyperX Pulsefire Haste 2 Wireless Mouse',
    priceUzs: 1100000, stock: 11, images: '[]',
    specs: '{"sensor":"HyperX 26K","dpi":"26000 DPI","pollingRate":"1000 Hz","weight":"61 g","connection":"2.4 GHz + Bluetooth","battery":"100 h","buttons":"6","warranty":"24 months"}',
  },
  {
    slug: 'hyperx-pulsefire-haste-2', kind: 'PERIPHERAL', category: 'mouse', brand: 'HyperX', model: 'Pulsefire Haste 2',
    nameRu: 'Мышь HyperX Pulsefire Haste 2', nameUz: 'Sichqoncha HyperX Pulsefire Haste 2', nameEn: 'HyperX Pulsefire Haste 2 Mouse',
    priceUzs: 820000, stock: 15, images: '[]',
    specs: '{"sensor":"HyperX 26K","dpi":"26000 DPI","pollingRate":"8000 Hz","weight":"53 g","connection":"USB","battery":"no","buttons":"6","warranty":"24 months"}',
  },
  {
    slug: 'asus-rog-harpe-ace-aim-lab-edition', kind: 'PERIPHERAL', category: 'mouse', brand: 'ASUS', model: 'ROG Harpe Ace Aim Lab Edition',
    nameRu: 'Мышь ASUS ROG Harpe Ace Aim Lab Edition', nameUz: 'Sichqoncha ASUS ROG Harpe Ace Aim Lab Edition', nameEn: 'ASUS ROG Harpe Ace Aim Lab Edition Mouse',
    priceUzs: 2060000, stock: 5, images: '[]',
    specs: '{"sensor":"ROG AimPoint","dpi":"36000 DPI","pollingRate":"1000 Hz","weight":"54 g","connection":"2.4 GHz + Bluetooth","battery":"90 h","buttons":"5","warranty":"24 months"}',
  },
  {
    slug: 'asus-rog-keris-ii-ace', kind: 'PERIPHERAL', category: 'mouse', brand: 'ASUS', model: 'ROG Keris II Ace',
    nameRu: 'Мышь ASUS ROG Keris II Ace', nameUz: 'Sichqoncha ASUS ROG Keris II Ace', nameEn: 'ASUS ROG Keris II Ace Mouse',
    descRu: 'Сенсор AimPoint Pro на 42 000 DPI и опрос 8000 Гц без проводов при весе всего 54 г.',
    descUz: '42 000 DPI’li AimPoint Pro sensori va simsiz 8000 Hz so‘rov — atigi 54 g vaznda.',
    descEn: 'A 42,000 DPI AimPoint Pro sensor and wireless 8000 Hz polling at just 54 g.',
    priceUzs: 2060000, stock: 4, images: '[]',
    specs: '{"sensor":"ROG AimPoint Pro","dpi":"42000 DPI","pollingRate":"8000 Hz","weight":"54 g","connection":"2.4 GHz + Bluetooth","battery":"108 h","buttons":"5","warranty":"24 months"}',
  },
  {
    slug: 'asus-tuf-gaming-m4-air', kind: 'PERIPHERAL', category: 'mouse', brand: 'ASUS', model: 'TUF Gaming M4 Air',
    nameRu: 'Мышь ASUS TUF Gaming M4 Air', nameUz: 'Sichqoncha ASUS TUF Gaming M4 Air', nameEn: 'ASUS TUF Gaming M4 Air Mouse',
    priceUzs: 620000, stock: 19, images: '[]',
    specs: '{"sensor":"PixArt PAW3335","dpi":"16000 DPI","pollingRate":"1000 Hz","weight":"47 g","connection":"USB","battery":"no","buttons":"6","warranty":"24 months"}',
  },
  {
    slug: 'corsair-m75-air-wireless', kind: 'PERIPHERAL', category: 'mouse', brand: 'Corsair', model: 'M75 Air Wireless',
    nameRu: 'Мышь Corsair M75 Air Wireless', nameUz: 'Sichqoncha Corsair M75 Air Wireless', nameEn: 'Corsair M75 Air Wireless Mouse',
    priceUzs: 2060000, stock: 6, images: '[]',
    specs: '{"sensor":"Marksman II 26K","dpi":"26000 DPI","pollingRate":"2000 Hz","weight":"60 g","connection":"2.4 GHz + Bluetooth","battery":"100 h","buttons":"5","warranty":"24 months"}',
  },
  {
    slug: 'corsair-harpoon-rgb-wireless', kind: 'PERIPHERAL', category: 'mouse', brand: 'Corsair', model: 'Harpoon RGB Wireless',
    nameRu: 'Мышь Corsair Harpoon RGB Wireless', nameUz: 'Sichqoncha Corsair Harpoon RGB Wireless', nameEn: 'Corsair Harpoon RGB Wireless Mouse',
    priceUzs: 690000, stock: 13, images: '[]',
    specs: '{"sensor":"PixArt PMW3325","dpi":"10000 DPI","pollingRate":"2000 Hz","weight":"99 g","connection":"2.4 GHz + Bluetooth","battery":"60 h","buttons":"6","warranty":"24 months"}',
  },
  {
    slug: 'redragon-m711-cobra', kind: 'PERIPHERAL', category: 'mouse', brand: 'Redragon', model: 'M711 Cobra',
    nameRu: 'Мышь Redragon M711 Cobra', nameUz: 'Sichqoncha Redragon M711 Cobra', nameEn: 'Redragon M711 Cobra Mouse',
    priceUzs: 340000, stock: 24, images: '[]',
    specs: '{"sensor":"PixArt PMW3325","dpi":"10000 DPI","pollingRate":"1000 Hz","weight":"125 g","connection":"USB","battery":"no","buttons":"7","warranty":"12 months"}',
  },
  {
    slug: 'glorious-model-o-2-wireless', kind: 'PERIPHERAL', category: 'mouse', brand: 'Glorious', model: 'Model O 2 Wireless',
    nameRu: 'Мышь Glorious Model O 2 Wireless', nameUz: 'Sichqoncha Glorious Model O 2 Wireless', nameEn: 'Glorious Model O 2 Wireless Mouse',
    priceUzs: 1370000, stock: 8, images: '[]',
    specs: '{"sensor":"BAMF 2.0","dpi":"26000 DPI","pollingRate":"4000 Hz","weight":"68 g","connection":"2.4 GHz + Bluetooth","battery":"110 h","buttons":"6","warranty":"24 months"}',
  },

  // ─────────────────────────── Гарнитуры ───────────────────────────
  {
    slug: 'hyperx-cloud-iii', kind: 'PERIPHERAL', category: 'headset', brand: 'HyperX', model: 'Cloud III',
    nameRu: 'Гарнитура HyperX Cloud III', nameUz: 'Quloqchin HyperX Cloud III', nameEn: 'HyperX Cloud III Headset',
    descRu: 'Легендарный комфорт серии Cloud: мягкие амбушюры с эффектом памяти и 53-мм динамики.',
    descUz: 'Cloud seriyasining afsonaviy qulayligi: xotira effektli yumshoq yostiqchalar va 53 mm dinamiklar.',
    descEn: 'Classic Cloud comfort: soft memory-foam cushions and 53 mm drivers.',
    priceUzs: 1370000, stock: 14, images: '[]',
    specs: '{"driver":"53 mm","frequencyResponse":"10–21000 Hz","detachableMic":"yes","surround":"DTS Headphone:X","anc":"no","connection":"3.5 mm + USB-C + USB","battery":"no","weight":"317 g","warranty":"24 months"}',
  },
  {
    slug: 'hyperx-cloud-iii-wireless', kind: 'PERIPHERAL', category: 'headset', brand: 'HyperX', model: 'Cloud III Wireless',
    nameRu: 'Гарнитура HyperX Cloud III Wireless', nameUz: 'Quloqchin HyperX Cloud III Wireless', nameEn: 'HyperX Cloud III Wireless Headset',
    priceUzs: 2060000, stock: 8, images: '[]',
    specs: '{"driver":"53 mm","frequencyResponse":"10–21000 Hz","detachableMic":"yes","surround":"DTS Headphone:X","anc":"no","connection":"2.4 GHz","battery":"120 h","weight":"330 g","warranty":"24 months"}',
  },
  {
    slug: 'hyperx-cloud-alpha-wireless', kind: 'PERIPHERAL', category: 'headset', brand: 'HyperX', model: 'Cloud Alpha Wireless',
    nameRu: 'Гарнитура HyperX Cloud Alpha Wireless', nameUz: 'Quloqchin HyperX Cloud Alpha Wireless', nameEn: 'HyperX Cloud Alpha Wireless Headset',
    descRu: 'До 300 часов работы от одного заряда — рекорд среди игровых гарнитур.',
    descUz: 'Bir marta quvvatlashda 300 soatgacha ishlash — o‘yin quloqchinlari orasida rekord.',
    descEn: 'Up to 300 hours on a single charge — a record among gaming headsets.',
    priceUzs: 2740000, stock: 6, images: '[]',
    specs: '{"driver":"50 mm","frequencyResponse":"15–21000 Hz","detachableMic":"yes","surround":"DTS Headphone:X","anc":"no","connection":"2.4 GHz","battery":"300 h","weight":"335 g","warranty":"24 months"}',
  },
  {
    slug: 'hyperx-cloud-stinger-2', kind: 'PERIPHERAL', category: 'headset', brand: 'HyperX', model: 'Cloud Stinger 2',
    nameRu: 'Гарнитура HyperX Cloud Stinger 2', nameUz: 'Quloqchin HyperX Cloud Stinger 2', nameEn: 'HyperX Cloud Stinger 2 Headset',
    priceUzs: 690000, stock: 20, images: '[]',
    specs: '{"driver":"50 mm","frequencyResponse":"10–28000 Hz","detachableMic":"no","surround":"DTS Headphone:X","anc":"no","connection":"3.5 mm","battery":"no","weight":"272 g","warranty":"24 months"}',
  },
  {
    slug: 'logitech-g-pro-x-2-lightspeed', kind: 'PERIPHERAL', category: 'headset', brand: 'Logitech', model: 'G Pro X 2 Lightspeed',
    nameRu: 'Гарнитура Logitech G Pro X 2 Lightspeed', nameUz: 'Quloqchin Logitech G Pro X 2 Lightspeed', nameEn: 'Logitech G Pro X 2 Lightspeed Headset',
    priceUzs: 3430000, stock: 5, images: '[]',
    specs: '{"driver":"50 mm graphene","frequencyResponse":"20–20000 Hz","detachableMic":"yes","surround":"DTS Headphone:X 2.0","anc":"no","connection":"2.4 GHz + Bluetooth + 3.5 mm","battery":"50 h","weight":"345 g","warranty":"24 months"}',
  },
  {
    slug: 'logitech-g435-lightspeed', kind: 'PERIPHERAL', category: 'headset', brand: 'Logitech', model: 'G435 Lightspeed',
    nameRu: 'Гарнитура Logitech G435 Lightspeed', nameUz: 'Quloqchin Logitech G435 Lightspeed', nameEn: 'Logitech G435 Lightspeed Headset',
    priceUzs: 1100000, stock: 16, images: '[]',
    specs: '{"driver":"40 mm","frequencyResponse":"20–20000 Hz","detachableMic":"no","surround":"Dolby Atmos","anc":"no","connection":"2.4 GHz + Bluetooth","battery":"18 h","weight":"165 g","warranty":"24 months"}',
  },
  {
    slug: 'logitech-g733-lightspeed', kind: 'PERIPHERAL', category: 'headset', brand: 'Logitech', model: 'G733 Lightspeed',
    nameRu: 'Гарнитура Logitech G733 Lightspeed', nameUz: 'Quloqchin Logitech G733 Lightspeed', nameEn: 'Logitech G733 Lightspeed Headset',
    priceUzs: 1780000, stock: 0, images: '[]',
    specs: '{"driver":"40 mm","frequencyResponse":"20–20000 Hz","detachableMic":"yes","surround":"DTS Headphone:X 2.0","anc":"no","connection":"2.4 GHz","battery":"29 h","weight":"278 g","warranty":"24 months"}',
  },
  {
    slug: 'logitech-g335', kind: 'PERIPHERAL', category: 'headset', brand: 'Logitech', model: 'G335',
    nameRu: 'Гарнитура Logitech G335', nameUz: 'Quloqchin Logitech G335', nameEn: 'Logitech G335 Headset',
    priceUzs: 820000, stock: 15, images: '[]',
    specs: '{"driver":"40 mm","frequencyResponse":"20–20000 Hz","detachableMic":"no","surround":"no","anc":"no","connection":"3.5 mm","battery":"no","weight":"240 g","warranty":"24 months"}',
  },
  {
    slug: 'razer-blackshark-v2-pro-2023', kind: 'PERIPHERAL', category: 'headset', brand: 'Razer', model: 'BlackShark V2 Pro (2023)',
    nameRu: 'Гарнитура Razer BlackShark V2 Pro (2023)', nameUz: 'Quloqchin Razer BlackShark V2 Pro (2023)', nameEn: 'Razer BlackShark V2 Pro (2023) Headset',
    descRu: 'Киберспортивная гарнитура с плотной шумоизоляцией и микрофоном Razer HyperClear Super Wideband.',
    descUz: 'Kuchli shovqin izolyatsiyasi va Razer HyperClear Super Wideband mikrofoniga ega kibersport quloqchini.',
    descEn: 'An esports headset with strong passive isolation and a Razer HyperClear Super Wideband mic.',
    priceUzs: 2740000, stock: 7, images: '[]',
    specs: '{"driver":"50 mm TriForce Titanium","frequencyResponse":"12–28000 Hz","detachableMic":"yes","surround":"THX Spatial Audio","anc":"no","connection":"2.4 GHz + Bluetooth","battery":"70 h","weight":"320 g","warranty":"24 months"}',
  },
  {
    slug: 'razer-blackshark-v2-x', kind: 'PERIPHERAL', category: 'headset', brand: 'Razer', model: 'BlackShark V2 X',
    nameRu: 'Гарнитура Razer BlackShark V2 X', nameUz: 'Quloqchin Razer BlackShark V2 X', nameEn: 'Razer BlackShark V2 X Headset',
    priceUzs: 550000, stock: 22, images: '[]',
    specs: '{"driver":"50 mm TriForce","frequencyResponse":"12–28000 Hz","detachableMic":"no","surround":"7.1","anc":"no","connection":"3.5 mm","battery":"no","weight":"240 g","warranty":"24 months"}',
  },
  {
    slug: 'razer-kraken-v3-x', kind: 'PERIPHERAL', category: 'headset', brand: 'Razer', model: 'Kraken V3 X',
    nameRu: 'Гарнитура Razer Kraken V3 X', nameUz: 'Quloqchin Razer Kraken V3 X', nameEn: 'Razer Kraken V3 X Headset',
    priceUzs: 690000, stock: 18, images: '[]',
    specs: '{"driver":"40 mm TriForce","frequencyResponse":"20–20000 Hz","detachableMic":"no","surround":"7.1","anc":"no","connection":"USB","battery":"no","weight":"285 g","warranty":"24 months"}',
  },
  {
    slug: 'razer-barracuda-x', kind: 'PERIPHERAL', category: 'headset', brand: 'Razer', model: 'Barracuda X',
    nameRu: 'Гарнитура Razer Barracuda X', nameUz: 'Quloqchin Razer Barracuda X', nameEn: 'Razer Barracuda X Headset',
    priceUzs: 1370000, stock: 10, images: '[]',
    specs: '{"driver":"40 mm TriForce","frequencyResponse":"20–20000 Hz","detachableMic":"yes","surround":"no","anc":"no","connection":"2.4 GHz + Bluetooth","battery":"50 h","weight":"250 g","warranty":"24 months"}',
  },
  {
    slug: 'steelseries-arctis-nova-pro-wireless', kind: 'PERIPHERAL', category: 'headset', brand: 'SteelSeries', model: 'Arctis Nova Pro Wireless',
    nameRu: 'Гарнитура SteelSeries Arctis Nova Pro Wireless', nameUz: 'Quloqchin SteelSeries Arctis Nova Pro Wireless', nameEn: 'SteelSeries Arctis Nova Pro Wireless Headset',
    descRu: 'Активное шумоподавление и две сменные батареи: одна работает, вторая заряжается в базе.',
    descUz: 'Faol shovqin bostirish va ikkita almashtiriladigan batareya: biri ishlaydi, ikkinchisi bazada quvvatlanadi.',
    descEn: 'Active noise cancelling and two swappable batteries: one in use while the other charges in the base.',
    priceUzs: 4800000, stock: 3, images: '[]',
    specs: '{"driver":"40 mm","frequencyResponse":"10–22000 Hz","detachableMic":"no","surround":"360° Spatial Audio","anc":"yes","connection":"2.4 GHz + Bluetooth","battery":"2× 22 h","weight":"337 g","warranty":"24 months"}',
  },
  {
    slug: 'steelseries-arctis-nova-7', kind: 'PERIPHERAL', category: 'headset', brand: 'SteelSeries', model: 'Arctis Nova 7',
    nameRu: 'Гарнитура SteelSeries Arctis Nova 7', nameUz: 'Quloqchin SteelSeries Arctis Nova 7', nameEn: 'SteelSeries Arctis Nova 7 Headset',
    priceUzs: 2470000, stock: 9, images: '[]',
    specs: '{"driver":"40 mm","frequencyResponse":"20–22000 Hz","detachableMic":"no","surround":"360° Spatial Audio","anc":"no","connection":"2.4 GHz + Bluetooth","battery":"38 h","weight":"325 g","warranty":"24 months"}',
  },
  {
    slug: 'steelseries-arctis-nova-1', kind: 'PERIPHERAL', category: 'headset', brand: 'SteelSeries', model: 'Arctis Nova 1',
    nameRu: 'Гарнитура SteelSeries Arctis Nova 1', nameUz: 'Quloqchin SteelSeries Arctis Nova 1', nameEn: 'SteelSeries Arctis Nova 1 Headset',
    priceUzs: 820000, stock: 17, images: '[]',
    specs: '{"driver":"40 mm","frequencyResponse":"20–22000 Hz","detachableMic":"no","surround":"360° Spatial Audio","anc":"no","connection":"3.5 mm","battery":"no","weight":"236 g","warranty":"24 months"}',
  },
  {
    slug: 'corsair-hs80-rgb-wireless', kind: 'PERIPHERAL', category: 'headset', brand: 'Corsair', model: 'HS80 RGB Wireless',
    nameRu: 'Гарнитура Corsair HS80 RGB Wireless', nameUz: 'Quloqchin Corsair HS80 RGB Wireless', nameEn: 'Corsair HS80 RGB Wireless Headset',
    priceUzs: 2060000, stock: 7, images: '[]',
    specs: '{"driver":"50 mm","frequencyResponse":"20–40000 Hz","detachableMic":"no","surround":"Dolby Atmos","anc":"no","connection":"2.4 GHz","battery":"20 h","weight":"367 g","warranty":"24 months"}',
  },
  {
    slug: 'corsair-virtuoso-rgb-wireless-xt', kind: 'PERIPHERAL', category: 'headset', brand: 'Corsair', model: 'Virtuoso RGB Wireless XT',
    nameRu: 'Гарнитура Corsair Virtuoso RGB Wireless XT', nameUz: 'Quloqchin Corsair Virtuoso RGB Wireless XT', nameEn: 'Corsair Virtuoso RGB Wireless XT Headset',
    priceUzs: 3700000, stock: 3, images: '[]',
    specs: '{"driver":"50 mm","frequencyResponse":"20–40000 Hz","detachableMic":"yes","surround":"Dolby Atmos","anc":"no","connection":"2.4 GHz + Bluetooth + USB-C + 3.5 mm","battery":"15 h","weight":"404 g","warranty":"24 months"}',
  },
  {
    slug: 'asus-rog-delta-ii', kind: 'PERIPHERAL', category: 'headset', brand: 'ASUS', model: 'ROG Delta II',
    nameRu: 'Гарнитура ASUS ROG Delta II', nameUz: 'Quloqchin ASUS ROG Delta II', nameEn: 'ASUS ROG Delta II Headset',
    priceUzs: 3150000, stock: 4, images: '[]',
    specs: '{"driver":"50 mm","frequencyResponse":"20–40000 Hz","detachableMic":"yes","surround":"7.1","anc":"no","connection":"2.4 GHz + Bluetooth + USB-C + 3.5 mm","battery":"110 h","weight":"318 g","warranty":"24 months"}',
  },
  {
    slug: 'asus-tuf-gaming-h3', kind: 'PERIPHERAL', category: 'headset', brand: 'ASUS', model: 'TUF Gaming H3',
    nameRu: 'Гарнитура ASUS TUF Gaming H3', nameUz: 'Quloqchin ASUS TUF Gaming H3', nameEn: 'ASUS TUF Gaming H3 Headset',
    priceUzs: 690000, stock: 0, images: '[]',
    specs: '{"driver":"50 mm","frequencyResponse":"20–20000 Hz","detachableMic":"no","surround":"7.1","anc":"no","connection":"3.5 mm","battery":"no","weight":"294 g","warranty":"24 months"}',
  },
  {
    slug: 'redragon-h510-zeus-x', kind: 'PERIPHERAL', category: 'headset', brand: 'Redragon', model: 'H510 Zeus X',
    nameRu: 'Гарнитура Redragon H510 Zeus X', nameUz: 'Quloqchin Redragon H510 Zeus X', nameEn: 'Redragon H510 Zeus X Headset',
    priceUzs: 620000, stock: 19, images: '[]',
    specs: '{"driver":"53 mm","frequencyResponse":"20–20000 Hz","detachableMic":"yes","surround":"7.1","anc":"no","connection":"USB","battery":"no","weight":"340 g","warranty":"12 months"}',
  },
]
